### ISSUE TITLE
Consumer delay when used with Producer on same runtime

### ISSUE THREAD

**Issue by thanpolas** [Blizzard/node-rdkafka#108]
Hello, I have created a script based on your tutorial to produce and consume on a single topic a single message.

https://gist.github.com/thanpolas/ed14e3db69646fefe268639ae069bbd5

When I run the script I get weird and unpredictable outcomes, sometimes there will be no data incoming at all, sometimes it will take several seconds to get the produced outcome (~25") and sometimes it'll work immediately. See screenshot of outcomes here: http://than.pol.as/iuB3

I understand that not cleanly shutting down consumers might be a reason why I observe these behaviors, would you confirm that too?

During development it is inevitable that a consumer will shutdown uncleanly, is there a solution for this, even if it is only for development env.

**Comment by webmakersteve** [comment]
The easiest way to get around the issue of kafka consumer delays is to set the consumer group to something different every time you spin up your application during development. This should greatly increase the initial stream of data because Kafka creates a new consumer group instead of trying to wait until a rebalance to add you to the pool.

**Comment by thanpolas** [comment]
I have updated [the script](https://gist.github.com/thanpolas/ed14e3db69646fefe268639ae069bbd5) to include a randomly generated Consumer-Group and add timestamps on each log that is happening. 

I am still getting weird behaviors, when run against both our "dev cluster" on AWS and local kafka container (fast-dev) the same script will almost never see the message consumed.

As it stays running, if I run the same screen from another console I can see the message in the first console, but then again, not in the second that created the second message.

I'd greatly appreciate it if you tried the script on your environment and let me know if you observe the same results or different.

**Comment by thanpolas** [comment]
I observe in your e2e/both test you produce with a delay of 2 seconds, if I imitate this, then the script works as expected, message consumed... So I'm guessing this has to do with the topic's message lifetime?

**Comment by webmakersteve** [comment]
Can you try setting the offset store reset to 'earliest'? It defaults to latest, which means kafka won't consume from the beginning of the topic, and instead will consume from the time it enters the consumer group.

`'auto.offset.reset': 'earliest'`

In general in your current implementation, it makes sense that you may not get the message because your consumer may not be in the group at the time a message is produced, and the group doesn't exist and have an offset stored to read from. Setting the reset to earliest should mean it will consume from the beginning.

**Comment by thanpolas** [comment]
The `'auto.offset.reset': 'earliest'` looks like to be the root of the issues i'm having, yet I cannot set it as a Consumer option. I have updated the gist I am running, here's what I get:

```
/Users/thanpolas/Projects/work/waldo/kafka-avro/node_modules/node-rdkafka/lib/client.js:54
  this._client = new SubClientType(globalConf, topicConf);
                 ^

Error: No such configuration property: "auto.offset.reset"
    at Error (native)
    at KafkaConsumer.Client (/Users/thanpolas/Projects/work/waldo/kafka-avro/node_modules/node-rdkafka/lib/client.js:54:18)
    at new KafkaConsumer (/Users/thanpolas/Projects/work/waldo/kafka-avro/node_modules/node-rdkafka/lib/kafka-consumer.js:88:10)
    at Object.<anonymous> (/Users/thanpolas/Projects/work/waldo/kafka-avro/temp/consumer-flow.js:25:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by webmakersteve** [comment]
This should be set as a topic config - not as a global config. That means it is the constructor parameter.

**Comment by thanpolas** [comment]
Got it, thank you very much @webmakersteve!
