### ISSUE TITLE
Breaking BC and Changelog

### ISSUE THREAD

**Issue by thanpolas** [Blizzard/node-rdkafka#120]
@webmakersteve from what I can see and understand by reading this commit ( 8ab9a73ab159d8886fcf639dc7cc72f3658aed02 ) breaks backward compatibility on the consumer interface?

And a new version has been released with the name `0.7.0-ALPHA.3` just a bump from previous `0.7.0-ALPHA.2` ... would it be possible to bump the "minor" part of the version so we are aware of breaking BC changes? `0.8.0-ALPHA.1` would seem appropriate here.

And it would be really awesome if the CHANGELOG was maintained so we can keep up with the updates without having to read PRs, commits and source code.

**Edit**: Fixed the SHA i wanted to refer to ( 8ab9a73ab159d8886fcf639dc7cc72f3658aed02 )

**Comment by webmakersteve** [comment]
Hi @thanpolas:

Working in a proper change log is something on the wish list. I'll try to keep one current as best I can.

Additionally, I published the last 'release' as an ALPHA release because it was pending a few other things, and not meant to be used except in circumstances where you needed the functionality added in the patches. I'd prefer releasing under `0.7.0` as we haven't had one yet, rather than bumping up to `0.8.0` immediately. If adding the `ALPHA` tag caused any confusion I will try to refrain from doing it in the future, but I needed to make an intermediary release for one of the patches.

**Comment by thanpolas** [comment]
Unfortunately `0.7.0-ALPHA.3` is the default version installed when doing `npm i node-rdkafka`. Which means that this is what users use... [You can use npm tags](https://coderwall.com/p/l_7acq/publish-beta-versions-of-npm-modules) to release alpha versions which will not be the default ver to be installed.

So, in this case, I am not 100% sure the changes you made really break BC, I am under the impression that they do, yet by changing the test expectations vs writing new ones is a sure way to let go of BC.

I'll get the chance to test this in the future and get back to you on that.

**Comment by webmakersteve** [comment]
In the future I'll make sure to be more careful about this. I apologize. It's definitely my intention to not make any breaking changes or deprecations in a patch release.

**Comment by webmakersteve** [comment]
Updated to 0.8.0 and used release notes as a change log, and I will continue to do this in the future. If I don't, reopen this and yell at me!
