### ISSUE TITLE
Topics not balanced between consumers of same group

### ISSUE THREAD

**Issue by michallevin** [Blizzard/node-rdkafka#160]
I am testing out a scenario I will need for my application, where several consumers in the same consumer group will read from several topics (each topic with 1 partition).

Although I have 3 consumers start consuming from the same topics, only 1 consumer "catches" all of the topics.

However, if 3 consumers start consuming from 1 topic with several partitions, they do seem to balance well.

From my understanding, Kafka is responsible for rebalancing and I have been able to successfully see the balancing of topics to different consumers in a different library, so is this a node-rdkafka bug?

I am using Kafka 0.10

```
var Kafka = require('node-rdkafka');

var topics = ['Test1', 'Test2', 'Test3', 'Test4'];

var consumer1 = new Kafka.KafkaConsumer({
  'metadata.broker.list': 'localhost:9092',
  'group.id': 'rdkafka-101',
  'enable.auto.commit': false
}, {
  'auto.offset.reset': 'beginning'
});

var consumer2 = new Kafka.KafkaConsumer({
  'metadata.broker.list': 'localhost:9092',
  'group.id': 'rdkafka-101',
  'enable.auto.commit': false
}, {
  'auto.offset.reset': 'beginning'
});

var consumer3 = new Kafka.KafkaConsumer({
  'metadata.broker.list': 'localhost:9092',
  'group.id': 'rdkafka-101',
  'enable.auto.commit': false
}, {
  'auto.offset.reset': 'beginning'
});

consumer1.on('ready', function(arg) {
  console.log('consumer ready.' + JSON.stringify(arg));
  consumer1.subscribe(topics);
  //start consuming messages
  consumer1.consume();
});

consumer1.on('data', function(m) {
  // Output the actual message contents
  console.log("consumer1: ");
  console.log("topic " + m.topic);
});

consumer1.on('disconnected', function(arg) {
  console.log('consumer disconnected. ' + JSON.stringify(arg));
});

//starting the consumer
consumer1.connect();

consumer2.on('ready', function(arg) {
  console.log('consumer ready.' + JSON.stringify(arg));
  consumer2.subscribe(topics);
  //start consuming messages
  consumer2.consume();
});

consumer2.on('data', function(m) {
  // Output the actual message contents
  console.log("consumer2: ");
  console.log("topic " + m.topic);
});

consumer2.on('disconnected', function(arg) {
  console.log('consumer disconnected. ' + JSON.stringify(arg));
});

//starting the consumer
consumer2.connect();

consumer3.on('ready', function(arg) {
  console.log('consumer ready.' + JSON.stringify(arg));
  consumer3.subscribe(topics);
  //start consuming messages
  consumer3.consume();
});

consumer3.on('data', function(m) {
  // Output the actual message contents
  //console.log(m.value.toString());
  console.log("consumer3: ");
  console.log("topic " + m.topic);
});

consumer3.on('disconnected', function(arg) {
  console.log('consumer disconnected. ' + JSON.stringify(arg));
});

//starting the consumer
consumer3.connect();
```

**Comment by webmakersteve** [comment]
You can't do this if you only have one partition. You need to have a minimum number of partitions as consumers for that topic in the group, otherwise some of them will do no work. 

If you want 3 consumers in the group consuming off a topic, give it at least 3 partitions.

**Comment by webmakersteve** [comment]
Didn't answer your other point effectively:

`node-rdkafka` consumers are stateless with one another. They are not really aware that the others exist. When kafka does assignments, it decides which consumer gets what. It isn't generally dependable to rely on topics being distributed across multiple clients, because topics are not the mechanism by which rebalances actually happen - it is topic partitions. 

When you subscribe to a list of topics you specify that you want to read data from all of them. When Kafka does its assignments, it only distributes on the partition level.

Other libraries that may have this behave differently are probably using more custom rebalancers that maintain state across multiple instances. But you should rely on partitions as the way to balance your consumers. You should always have, at minimum, a number of partitions >= number of concurrently connected clients if you want equal distribution in that topic.

**Comment by michallevin** [comment]
@webmakersteve thank you very much for your detailed answer.

**Comment by webmakersteve** [comment]
Closing issue. Re-open it if you still need help!
