### ISSUE TITLE
Allow passing a callback to commit/commitMessage

### ISSUE THREAD

**Issue by mimaison** [Blizzard/node-rdkafka#172]
Following https://github.com/Blizzard/node-rdkafka/pull/145 we don't have a way to provide a callback when using `commit()` and `commitMessage()`.

It would be useful to add this back in order to allow checking the result of the commit operation.
Also the docs seem out of date:
https://blizzard.github.io/node-rdkafka/current/KafkaConsumer.html still mentions 
`commitMessage(msg, cb)`

**Comment by webmakersteve** [comment]
Will update the docs. As for the commit callback, it will probably come back by using `librdkafka`'s `offset_commit_cb`. That is, it will be a separate event raised on the consumer rather than a callback.

I could bring back the old functionality, which was to just spin up an asynchronous worker and call commitSync, but it actually had some issues with race conditions and has no mechanism by which I can provide a timeout, which may cause it to block forever. 

Would having an `offset.commit` event be good enough for your use case?

**Comment by edoardocomar** [comment]
yes thanks Steve!

**Comment by edoardocomar** [comment]
@mimaison I think this issue can be closed thanks to
https://github.com/Blizzard/node-rdkafka/pull/185
