### ISSUE TITLE
Consume with a size, cb does not appear to do anything

### ISSUE THREAD

**Issue by jmwilkinson** [Blizzard/node-rdkafka#176]
Calling the following code:

```
        this.consumer.on('ready', function() {
            console.log(`Subscribing to ${this.topic}`);

            this.consumer.subscribe([this.topic]);

            console.log(`Consuming topic`);

            this.consumer.consume(5, function (err, data) {
                console.log(err);
                console.log(data);
            });
        }.bind(this));
```

Nets this result:
```
Subscribing to test-topic
Consuming topic
null
[]
Disconnecting
```

Looking at the consumer group data, I have 245785 records of lag. Running the code without specifying the size will correctly spew out data.

**Comment by webmakersteve** [comment]
This perhaps is deserving of a documentation change, but consuming a number of records will either give you a number of records, up to the number of records you have requested. 

If the array it give you is of length 0 and you are certain you have messages, it is because the requests are timing out. This means that Kafka is not ready to begin giving you messages, generally.

Consume calls to kafka wait on you being assigned a list of assignments by the group coordinator. The group coordinator tries to batch reassignments together, and waits up to half (or so) of a heartbeat interval to do those assignments. This is usually about 30 seconds.

When you call consume with a number, you are expected to do the logic to constantly be calling the function, like so:

```js
const consumer = this.consumer;

function processRecords(data, cb) {
  if (data.length == 0) {
    return setImmediate(cb);
  }
  
  // do work
  setImmediate(cb);
}

function consumeNum() {
  consumer.consume(5, (err, data) => {
    if (err) {
      console.error(err);
      return;
    }

    processRecords(data, () => {
      consumeNum();
    });
  });
}

consumeNum();
```

Just wrote this by hand, but that's sort of the idea. Alternatively, you can use the read stream which does this work for you.

**Comment by jmwilkinson** [comment]
The difficulty I have with the stream API is that it doesn't seem like there is a way to only commit the offset after the messages have been processed. I can't even find any way to "signal" the end of processing for a message, since streams are using an event model.

So my understanding of your code and explanation is that when using `consume` with a size parameter, you will receive 0 records for perhaps about 30 seconds while "things" get situated, after which you should begin consuming "normally", until you hit 0 records again. Is that correct?

**Comment by webmakersteve** [comment]
That is correct. 

Additionally, the stream does not auto commit offsets unless you specify that option. It streams in object mode, so if you were to do this:

```js
consumer.getReadStream(...)
  .on('data', (msg) => {
    console.log(msg.offset);
  });
```

You would still be able to do your processing and committing when the processing was done.  It would work similarly when using the pipe interface.

**Comment by jmwilkinson** [comment]
So based on your example, I have my code more or less working. I just have one problem I'm really confused about. When I try to commit, I get the error: `undefined is not a function`.

My code to commit is pretty simple:
```
this.consumer.commit();
```

I have `enable.auto.commit` set to false, and am still using the `consume` function with a size parameter. Is there some odd behavior around calling a manual commit when doing this?

**Comment by jmwilkinson** [comment]
Thanks. I basically have it working, except I'm getting the following error:

`error: uncaughtException: undefined is not a function`

This is a direct result of my calling:

`this.consumer.commit()`

It looks like this is caused somewhere internal to the library, in the function KafkaConsumer:444

`this._client.commit(cb)`

I am not certain what function it is trying to call. Can you verify that the commit function works as expected and I do not need anything else to call it?

**Comment by jmwilkinson** [comment]
Closing this. It looks like I was using an older version of the library, and I've since updated and am seeing a different problem, as outlined in #184
