### ISSUE TITLE
Consumer "commit" hangs, does not execute callback.

### ISSUE THREAD

**Issue by jmwilkinson** [Blizzard/node-rdkafka#184]
I am using version 0.10.2.

The following code hangings waiting for the commit call to complete.

```
return new Promise( function (reject, resolve) {
    this._log.info('Calling commit');
    this.consumer.commit( (err) => {
        if(err) reject(err);
        else resolve();
    })
}.bind(this))
.bind(this)
.then( () => {
    this._log.info('Commit finished');
});
```

According to the documentation, I should be able to pass a callback as the first function to be called when committing all offsets.

I had a variation of this code working with an earlier version of the library, where I manually specified which topic/partitions/offsets I wanted to commit. That also just hangs.

Am I calling this function correctly? Is there a bug somewhere in that logic?

**Comment by rakshitajain5** [comment]
You can try commiting like this. This is working for me  -
 
`consumer.commit({ topic: data.topic, partition: data.partition, offset: data.offset + 1 }, function(err, data) {})`

**Comment by webmakersteve** [comment]
Unfortunately new versions of `node-rdkafka` do not take a callback parameter for commit. Where are you reading the docs that state you can? The interface has changed.

I am going to implement `offset_commit_cb` so you will be able to be notified when commits go through, but since `commit` uses `librdkafka`'s `commitAsync` under the hood and is non blocking, I removed the callback as it is unnecessary.

**Comment by jmwilkinson** [comment]
@webmakersteve Docs are taken from this page: https://blizzard.github.io/node-rdkafka/current/KafkaConsumer.html

Under the section `Parameters`, it states: 

```
Parameters:

Type	Description
object | function	Topic partition object to commit or callback if you are committing all topic partitions.
function	Callback to fire when committing is done.
```

If a callback is truly unnecessary, how could one achieve the following behaviour:

1. Consume *n* messages
2. Perform some operation on them
3. Commit the new offsets
4. Repeat step one

This must be done sequentially, or there is opportunity to get out of "sync". For instance, you may want to consume one message at a time, and not get the next message until the first has been processed- this is, in fact a use-case of mine- and without the ability to consume only after a commit is finished, it is impossible to achieve "at least once" behaviour.

**Comment by webmakersteve** [comment]
What you're describing that you're looking for is not at least once, it's at most once. Imagine this scenario:

1. Consume _n_ messages
2. Perform operations on them
3. Run commit. By virtue of running commit it has queued a commit request in librdkafka's internal request buffer
4. Repeat

Let's imagine a situation where commit has failed, and we have no callback to tell us it failed since we have queued it off for processing later. 

If the application crashes and the commit never went through, when you start it again, you will re-read messages you have processed. Still so far at least once behavior.

If the application crashes directly after the first commit has gone through, you will start reading where you left off with each message arriving only once.

No matter what, as long as you have queued commit up when you are done processing the batch of messages, you will get at least once behavior (as long as auto commit is off). 

If, for some reason, you need to ensure that the commit has gone through and you will not do anything in that process until it does, you can use `commitSync`, but I really don't think your use case is one that requires it. If at least once is okay, you will always get it with `commit`.

**Comment by jmwilkinson** [comment]
I guess I don't know how the commit gets queued/processed. If the queued commits only references offsets at the time it was queued, then you're correct. If it pulls offsets when the commit actually executes, then there would be potential to commit unprocessed offsets, which would be lost if the processing fails.

Even in the first scenario, if we commit and then immediately consume and process the next batch of messages, the number of messages we would potentially reprocess increases by the number of consumes before the commit fails. So if we consume 3 batches of 200 messages before the first commit fails, we now have 600 duplicate messages rather than just 200. This is not optimal.

If we use commitSync, however, and we have multiple background processing activities, won't those be blocked until the commit finishes? So if we have one sequential processing activity and one non-sequential, the non-sequential activity would still have to block until the commit is finished, which is also non-optimal.

**Comment by webmakersteve** [comment]
> I guess I don't know how the commit gets queued/processed. If the queued commits only references offsets at the time it was queued, then you're correct. If it pulls offsets when the commit actually executes, then there would be potential to commit unprocessed offsets, which would be lost if the processing fails.

Commit will commit the head of each topic partition that have been passed through the consume call. So calling commit will first get the current offsets, and then queue a commit for those offsets to be processed during the next fetch.

> Even in the first scenario, if we commit and then immediately consume and process the next batch of messages, the number of messages we would potentially reprocess increases by the number of consumes before the commit fails. So if we consume 3 batches of 200 messages before the first commit fails, we now have 600 duplicate messages rather than just 200. This is not optimal.

Correct. But this is by design. Kafka is intended to work this way generally. Commits are not like acking a message in rabbit - they are meant to be a best effort sort of thing. Additionally, if the commit fails for a non-recoverable reason, it means a subsequent fetch will also fail. The commit gets queued to be processed during the next request to the broker. If you then try to consume, it does a fetch request, and commit should get executed first anyway.

> If we use commitSync, however, and we have multiple background processing activities, won't those be blocked until the commit finishes? So if we have one sequential processing activity and one non-sequential, the non-sequential activity would still have to block until the commit is finished, which is also non-optimal.

Correct. This is why I generally do not recommend using it. It will block the v8 thread until it completes execution. I really do think the regular commit method will be good enough for your use case, however.

To give you a bit of background on why commit no longer has a callback:

We originally had commit run `commitSync` under the hood on a spawned v8 worker thread, and then callback when it finished. But `commitSync` (the `librdkafka` commitSync) has a lot of inherent problems. Kafka fetches get blocked while it tries to commit, and if a rebalance event or broker change happens in between, the commit ends up failing because it is committing to the wrong broker, offset, partition, etc. It ended up blocking all consumption because it was using outdated metadata. 

It was a hard case to reproduce, but by going with the recommended way (as far as I can tell) and using `commitAsync`, librdkafka gets the offsets now, but generates the bulk of the commit message when it is time to make a request. This allows for it to change its internal metadata store before it actually runs the commit if it is in the middle of an operation, and this "fixed" the bug.

**Comment by jmwilkinson** [comment]
Thanks, that certainly helps clarify things, especially the point about commits occurring before a fetch. The history also gives me a much clearer idea of what is happening. Much appreciated.

I'm also running into a producer issue `Error: Local: Queue full`. Should I open a new thread about this?

**Comment by webmakersteve** [comment]
Are you running `poll` on a regular interval? The easiest way is to use `producer.setPollInterval(interval)`

**Comment by jmwilkinson** [comment]
I was not doing that. Is there a recommended interval for this? What is the impact of poll on the queue getting flushed?

**Comment by webmakersteve** [comment]
It's an additional request to the broker. Producers without acks normally get no response from brokers when they do their business so they don't know if messages have been received. Poll hits the producers and gets updates for delivery reports, which allows it to mark things as processed.

You basically want to tune it so your queue never gets full, but you aren't running it too much. We use 5 seconds generally in our applications.

**Comment by webmakersteve** [comment]
Poll is a non blocking call, so there is little to no impact in calling it often. A lot of librdkafka wrappers call poll implicitly in every produce. I elected to keep them separate for optimization purposes.

**Comment by jmwilkinson** [comment]
Good info, thanks for the timely responses. Hopefully this will help anyone encountering similar issues in the future.
