### ISSUE TITLE
Question about behavior of unsubscribe()

### ISSUE THREAD

**Issue by ottomata** [Blizzard/node-rdkafka#21]
I see that [`Consumer::Unsubscribe`](https://github.com/Blizzard/node-rdkafka/blob/master/src/consumer.cc#L227-L229) returns `RdKafka::ERR__STATE` if it is called on a not-yet-subscribed consumer.  However, there doesn't seem to be a way to infer subscription state via the node client.  Should I manage this state myself, or can we add a `consumer.subscriptions()` method to get the current subscriptions? And/or, perhaps `Consumer::Unsubscribe` should just be a no-op if the consumer has no current subscriptions.

While looking into this, I noticed that `consumer.subscribe()` [takes a cb](https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer.js#L143), but as far as I can tell it is not invoked.  Should it be?

**Comment by webmakersteve** [comment]
Originally, unsubscribe was idempotent and you could call it as many times as you want because it didn't matter if you actually were subscribed, but I changed that behavior because I thought it encouraged not caring about the state. I think the C++ should still throw but that this behavior should be encapsulated in the JS part of the library. 

About the callback: I think that's a remnant from an old version where subscribe was async. I found that there wasn't really much of a reason for it so I changed it to sync. I'll make sure to update the docs and remove the parameter.

**Comment by webmakersteve** [comment]
Unsubscribe will no longer throw when you are not currently subscribed. I believe this satisfies the issue!
