### ISSUE TITLE
consumer.subscribe method - use case to support topic and partitions...

### ISSUE THREAD

**Issue by pdykes** [Blizzard/node-rdkafka#214]
I have a use case, that seems more common as I read about kafka.  Currently, the api supports the consumer api: <consumer>.subscribe(topics) where topics are a list of 1 or more strings. However, I want the client (just like the producer can write to a specific Topic/Partition in the API) to be able to specify not only which topic, but also which specific partition it listens to. This is needed since some cloud vendors limit the number of topics, and for moderately complicated solutions, that topic specific limit is an issue.  Also, I have some topics that have a few very chatty producers (writing to a specific partition) and consumers (who would need to use the rebalance_cb). The overall design makes sense for that partition to fit in within a topic, but I don't want to have other consumers have to handle the processing to listen to that flow unnecessarily.  Net,  if one consumer can be assigned to listen to a specific topic, then they should be able to further listen to a specific partition or small partition range just as the produce can write (without implementing the rebalance_cb callback) (producers can't write to a range, so I'm ok with specifying a specific partition to read from vs. a range).  This allows architectural consistency for a client only listen to a specific partition and a tighter consumer API which has issues using the current approach I am running into as a user.  Currently, the user has to leverage the rebalance_cb..., this api seems overly complicated, and there are issues with this and how the values are used causes the library core dumps, etc... To start, this can be static approach, e.g. does not have to be dynamic during life of the client consumer, and could be restricted to one consumer reading from one topic/partition or a partition subset if that would help implement it. This overall solution may make more sense for complicated topic/partition design scenarios or where kafka providers limit some aspect, as in this case a specific set of topics. Net, I propose an extension called <consumer>.subscribe(topicPartitions) [same api, just takes different data type than list of string topics] or another subscribe API such as subscribeTopicPartitions(topicPartitions).  Either api would take a very specific, well documented and tested  object parameter in the form an object, for example an array value = [{topic: 'sometopic', partition: '1' (or a range, e.g. '1-3' }, { topic: 'nexttopic', partition '1'}].  Lastly, it seems the Java api allows a user to subscribe and via a property value enumerate the specific partition(s) the consumer should read from optionally, and python posts refer to something, but I did not verify that language binding.

**Comment by webmakersteve** [comment]
Hi there. Thanks for your suggestion. I totally understand your use case, but it goes against the nature of what subscribe actually is.

This is the `KafkaConsumer` logic when using subscribe. Going to use 2 clients in the example

1. Client 1 connects to Kafka. It was configured to use the group id "group"
2. Kafka accepts the connection. It is now managed at the TCP socket level - just gets reaped like regular TCP connections when it is idle too long
3. You call subscribe on your node-rdkafka client. You want `topic` and `topic2` to be subscribed to.
4. Client 1, acknowledging the successful connection, submits a group join request. It specifies the group id "group" and encodes its requested subscription into a binary payload to be broadcasted.  
5. Kafka waits to stack the rebalance in case any other consumers are looking to join
6. Client 2 connects to Kafka. It does steps 1-4 just like the first client did
7. Kafka is satisfied with how long it has waited. It elects a consumer group leader among the clients. It chooses client 1.
8. Client 1 is given a payload from kafka specifying the consumers in the group and their active subscriptions. It also has the metadata from kafka with specifies all the topics on the cluster and their partitions, leaders, ISRs, etc.
9. Client 1 does its partitioning assignment strategy (in librdkafka it is either range or round robin) to give out all the assignments for each requested subscription to each client. It responds to kafka with a payload to be routed to each client.
10. Client 1 begins consuming on the topic partition list it has come up with for itself
11. Kafka sends client 2 the assignment client 1 has come up with for it. It begins consuming on its topic partition list. It knows how to understand the payload because it is also a node-rdkafka (librdkafka) consumer.

So, as you see, under the hood each consumer is reading from partitions and topics. In fact, this interface is exposed to you if you use the `assign` method instead of subscribe. Subscribe makes all of this rebalancing and partitioning seamlessly managed under the hood in case you just want to generically distribute your partitions across all the clients you have available. 

If you want to avoid this type of assignment, just don't use subscribe, and use `assign` :)

**Comment by pdykes** [comment]
Agree with your comments, key thing on my side, did not know <consumer>.assign() was an API I could call ;-).  Makes the world of difference.  I was using the rebalance_cb approach, and the assign() method there, and getting librdkafka segmentation faults.  This method has worked like a charm, but one thing just to clarify...

Thanks to your post, I have mocked it up test code in one producer and  3 consumers, and as the producer dynamically and randomly writes to each consumer, the correct and specific kafka consumer does receive their messages and ONLY their messages.  

However, you said "If you want to avoid this type of assignment, just don't use subscribe, and use assign :)", but when I give each client their own group-id, and use this api: 

```
            kafka_consumer.assign([{
                topic: 'multi-partition-topic',
                partition: unique_partition_to_listen_only
                }]);
```

The listeners don't get anything... What has worked after some experimentation (each client listening to unique partition within the same topic) is the following:

```
        kafka_consumer.subscribe(['multi-partition-topic']);
        kafka_consumer.assign([{
                topic: 'multi-partition-topic',
                partition: unique_partition_to_listen_only
                }]);
```
I can verify receiving the events in the various client reading a specific partition after the producer writes to that partition.

Net, seems I need to use subscribe and assign together to make this work vs. being separate constructs, or am I doing thing this incorrectly and getting the behavior I'm looking for? (lucky me, usually does not work that way when i prototype ;-)).

Thanks in advance.  I'll close this once I hear back, i think I'm good.

Perry

**Comment by edoardocomar** [comment]
@pdykes 
- you should not mix subscribe and assign as they are respectively the high-level/ kafka-group way of consuming and the low-level one
- using only assign you need to set an offset - which either you had saved in Kafka or you managed yourself.
-if using Kafka-saved offsets, the trick is to call assign twice, else `committed` won't return you the data you need

```
var Kafka = require('../');

var consumer = new Kafka.KafkaConsumer({
  //'debug': 'all',
  'metadata.broker.list': 'localhost:9092',
  'api.version.request' : true,
//  'rebalance_cb' : true,
  'group.id': 'my-example-group',
  'enable.auto.commit': false,

  'offset_commit_cb' : function(err, offsets) {
    console.log("in offset_commit_cb", err, offsets);
  }
});

var topicName = 'testtopic';

//logging debug messages, if debug is enabled 
consumer.on('event.log', function(log) {
  console.log(log);
});

//logging all errors
consumer.on('event.error', function(err) {
  console.error('Error from consumer', err);
});

//counter to commit offsets every COMMIT_EVERY_NUM are received
var counter = 0;
const COMMIT_EVERY_NUM = 7;

consumer.on('ready', function(arg) {
  console.log('consumer ready.' + JSON.stringify(arg));

  consumer.assign([{ topic:topicName, partition:0}]);
  //consumer.subscribe([ topicName ]);

  consumer.committed(5000, function(err, topicParts) {
    console.log("committed cb", err, topicParts)
    consumer.assign(topicParts);
    consumer.consume();
  });

});


consumer.on('data', function(m) {
  counter++;

  // Output the actual message contents
  try {
    console.log("received:", JSON.stringify(m));
//  console.log(m.value.toString());
  } catch (e) {
    console.log(e);
  }
//  console.log("position: " + JSON.stringify(consumer.position()));
//  consumer.committed(5000, function(err, topicParts) {
//    console.log("committed cb: "+ JSON.stringify(err) + " " + JSON.stringify(topicParts))
//  });
  
  //committing offsets every numMessages
  if (counter % COMMIT_EVERY_NUM === 0) {
    console.log('calling commitMessage on', JSON.stringify(m));
    consumer.commitMessage(m);
  }

});

consumer.on('disconnected', function(arg) {
  console.log('consumer disconnected. ' + JSON.stringify(arg));
});

//starting the consumer
consumer.connect();

//stopping this example after 30s
setTimeout(function() {
  consumer.disconnect();
}, 3000000);
```

**Comment by pdykes** [comment]
Thanks so much, seriously. I'll run with this then.

One suggestion, it maybe useful to add these features, tradeoffs, concepts and examples to the Node docs  for users to better understand the capabilities.  While potentially a bit lower level in approach based on above commentary, this seems to help give Node more functional parity to the Java and Python API options and does give straightforward approach to address the issue I was working to resolve.

The assignment of topic/partition concept that Node's assign interface provides seems present in the Java API without the "low level" approach but maybe I have not looked at enough examples and the same style be needed to accomplish?  In Java, seems like you set the property of topic/partition, and the API usage remains consistent, but as always, buyer beware.

I am partial partial to Node for many non-kafka reasons, so I'll take this approach for now. I'll work with this for a while, and if solid, I can also provide back some docs, examples, etc... as well.  Appreciate the help.

Regards, 
Perry

**Comment by edoardocomar** [comment]
@pdykes the "low-level" direct assignment and the "high-level" subscription based approaches are Kafka-centric, and pretty much surfaced similarly in Java/Node/anything. 
The only node-specific bit is that trick of calling assign twice AFAIK
