### ISSUE TITLE
Client.isConnected continues to return true after connection

### ISSUE THREAD

**Issue by alsiola** [Blizzard/node-rdkafka#217]
In trying to create a healthcheck endpoint for an API I wish to ascertain the connection status of any Kafka clients.  I thought to accomplish this with `producer.isConnected()` / `consumer.isConnected()`.

If I start the application, then all is fine.  If I then kill my Kafka container then, as expected, I get errors logged from `event.error` listeners.  However, if I call `isConnected()` then it still returns true.

**Comment by webmakersteve** [comment]
`isConnected` does not tell you the state of the broker - it just says whether node is connected to a librdkafka instance. All of the socket retrying, pooling, and management is abstracted away from the consumer of the library.

The reason the `isConnected` call exists is because I need to call "`connect`" to create a librdkafka class instance, which immediately opens a socket. It will only ever return false if you manually disconnect. 

If you want to check internal broker state I recommend calling `getMetadata` on intervals and ensuring the call does not error. You can use that to keep an internal state variable to say whether it is working. Unfortunately there isn't much else I can do on hte node side to make this better.

**Comment by alsiola** [comment]
Thanks for the recommendation, I'll go with that approach.

**Comment by Vidz51** [comment]
whats the difference between isConnected and isConnecting in producer
