### ISSUE TITLE
V2 - Removal of topic objects

### ISSUE THREAD

**Issue by michallevin** [Blizzard/node-rdkafka#264]
Can someone clarify what the removal of topic objects affects?

I am using V2 and would like to use one producer stream to write to several topics. I am using the `objectMode` = true to do so and it looks like it's working and want to make sure it doesn't have to do with the removal of topic objects (since I am not sure what that refers to and sounds related)

Thanks in advance!!

**Comment by webmakersteve** [comment]
The topic objects that change talked about were the wrapped `librdkafka` topic objects that the library used under the hood. They were reference counted internally by the library, and v8 made it very difficult to garbage collect them properly because of that, so they were removed in favor of using just topic names.

Specifying a topic inside an object is fine, but topic-specific config is no longer supported. You should use the topic configuration parameter to specify that now, which means you will need a separate producer/consumer for each unique variant of topic configuration in your application.

**Comment by michallevin** [comment]
@webmakersteve Good news, thank you. Where was it previously possible to define topic-specific config?

**Comment by webmakersteve** [comment]
You could run:

```js
const topicConfig = {};
const topic = producer.Topic('topicName', topicConfig);

producer.produce(topic, ...);
```
