### ISSUE TITLE
what is options.highWaterMark?

### ISSUE THREAD

**Issue by evollu** [Blizzard/node-rdkafka#270]
When I use ConsumerStream and set fetchSize 5, the stream fetches 7 items at a time. Looked around the code and find this 
https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer-stream.js#L82

There is no documentation about what `highWaterMark` is and why it is 2.

Can anyone explain what it does and why +2?

**Comment by webmakersteve** [comment]
https://nodejs.org/api/stream.html#stream_buffering

High watermark is a built in feature of node's streams that determines how large the buffer should be for storing data. I have added +2 to it to ensure it can fit an entire fetch set + a little extra. 2 was arbitrarily chosen but I did not want the fetch size to be the same as the buffer size. 

It looks like push is succeeding until the buffer is full which is why you're getting 7 at a time there, but the fetch size is supposed to be sort of independent on how many messages you're reading at a time. 

You can override the watermark to change the size of the buffer in your stream.

**Comment by evollu** [comment]
correct me if I'm understanding wrong.
libkafkaClient.consume() should be called with 5 even when node stream buffer is set to 7 right? otherwise it will be the same setting highWaterMark to 5.
But actually consume is called with 7.

**Comment by webmakersteve** [comment]
You're right. It's because the `size` that is being passed into the consume method is being called with high watermark which is being adjusted. 

I think it may make sense to get rid of fetch size to allow node to read as much as the stream needs to fill up.

**Comment by evollu** [comment]
fetch size is useful for me because I want to do batch operation in consumer.

**Comment by webmakersteve** [comment]
https://github.com/Blizzard/node-rdkafka/commit/30f2e16e56dbbc2477c87271b6f040451dd146a2

I changed the code a bit to honor the option better.

**Comment by evollu** [comment]
greate! thanks
