### ISSUE TITLE
Is there any reconnect event if broker is reconnected 

### ISSUE THREAD

**Issue by krishanfrog** [Blizzard/node-rdkafka#311]
If I start my producer and then kill the broker, an "error" event is triggered immediately. 

Is there any way to know if the connection to the broker is reestablished once I bring the broker up again? The "ready" event is triggered just once when the process is initially started

Asking this because once I get a delivery report error for a message it doesn't get resent automatically upon reestablishing the connection - so need to resend it manually once connection to broker is reestablished.

**Comment by webmakersteve** [comment]
If the initial metadata fetch fails, `node-rdkafka` will not automatically reconnect. You should respond to this in your app specific manner in the connect callback. 

There is currently a PR to add an emitted event when that happens, like `connect.failure` or something, so it should make it a little easier to respond to these issues especially when you omit the callback in the connect method.

**Comment by krishanfrog** [comment]
Got it. Didn't know about the callback option in connect(). That is helpful.

But if the initial connection is successful and then broken (when broker is down) and then reconnected (once its brought back up), is there an event triggered when node-rdkafka automatically reconnects to the brokers? This way the application can know a reconnect has occurred.

**Comment by webmakersteve** [comment]
There is no event raised specifically for re-connects to brokers, but you should not have to worry about it too much. That is all handled under the hood.

Disconnecting from kafka is a non failure case because the way it is distributed, so even if it happens it should not impact your application much. The only time it is a problem is if all your brokers are down (or the leader and all replicas for a partition are down). Those errors are bubbled up in the error callback, but not as particular errors.

Even still, they too should be solved automatically when the broker outage is fixed.
