### ISSUE TITLE
Pm2 server restart if no matching compression algo at consumer end.

### ISSUE THREAD

**Issue by tarunrazdan** [Blizzard/node-rdkafka#329]
We have a Kafka cluster running with lz4 compression.

Pm2 server restarts itself without giving any error information if the compression of packets consumed by the Kafka consumer doesn't match.

To reproduce:
1. Install node-rdkafka without installing the liblz4-dev library.
2. Everything will run smoothly.
3. Now as soon as the packet arrives/consumed, the pm2 server restart itself, without giving any error.

**Comment by webmakersteve** [comment]
It is probably core dumping without that dependency. It is building (likely) because it is finding header files somewhere but it isn't able to link at run time. 

This is just the nature of using C++ unfortunately. Check your core dumps directory and see if there are any node processes there. I think the default is `/var/lib/core`?
