### ISSUE TITLE
Performance issues when running multiple node-rdkafka instances

### ISSUE THREAD

**Issue by csaroff** [Blizzard/node-rdkafka#332]
Hey Steve,

I have an application that creates ~80 node-rdkafka consumers(and growing) using non-flowing mode.  Each consumer fetches a batch of 100 messages, does some processing and then commits.

We're seeing some performance issues with the application including data consumption latency(consumedAt - producedAt).  Running the application with just one node-rdkafka consumer, the latency is on the order of 4 seconds, but with 77 consumers, the latency grows to around 60 seconds.

We noticed that our application is spawning almost 1000 threads(many of which are labeled as "rd_kafka_broker_thread_main").  We ran some v8 profiles using [0x](https://www.npmjs.com/package/0x) and (separately) the [--prof-process flag](https://nodejs.org/en/docs/guides/simple-profiling/).

![image](https://user-images.githubusercontent.com/7225723/34507365-1cebc7da-efea-11e7-92c6-9f20d317da48.png)
![image](https://user-images.githubusercontent.com/7225723/34507367-24c95bf2-efea-11e7-9446-211268619d66.png)

It seems most of the cpu cycles are being spent in system calls to libsystem_kernel.dylib.  My guess is that so many extra threads are causing starvation which leads to some consumers being a bit further behind on actually consuming data.

The reason for needing so many node-rdkafka instances is that we want to consume from a topic using different group ids(which afaik can only be accomplished using multiple node-rdkafka instances).

Is this way outside the intended scope of this module?  Any advice or help here would be greatly appreciated.

**Comment by webmakersteve** [comment]
The performance is going to degrade quite a bit with multiple consumers. One of the reasons is because how JavaScript does multithreading. Events can be pushed to the main libuv thread to be executed on the single threaded js context. This means each consume call buffers the messages it has available. Additionally, each time you call consume it needs to queue that up to be executed on a libuv worker thread. By default there are only 4 of these. You can increase the number of worker threads with an environment variable `UV_THREADPOOL_SIZE`. 

The other problem will be allocations. The most expensive part of node-rdkafka (and one of the reasons why its performance lags so much behind the raw C++ library behind it), is because it needs to double allocate buffers for messages. When you have 80 consumers reading the same topics, you are allocating each message 160 times (essentially). It would be better if you could route the messages 1 to n times to where they need to go rather than relying on kafka with different groups to do it, but I'm not sure what your use case is.

Next, is network. Network is usually the biggest bottleneck in Kafka consumers because the consumers are pretty simple. With all of those consumers there will be a lot of network saturation, which will cause pretty big performance penalties as all of the consumers try to get their slice of network bandwidth. 

And last one worth mentioning is just threading. Each consumer will be a minimum of one highly active thread. There will be a lot of thread contention across multiple consumers, and I think there are even places in `librdkafka` where it uses global locks that will cause lock contention across multiple processes.

If you explain your use case a little more maybe we can come up with a better solution.

**Comment by csaroff** [comment]
@webmakersteve Thank you so much for the extensive right up!

> You can increase the number of worker threads with an environment variable UV_THREADPOOL_SIZE
We've actually had this set to 128 for a long time trying to resolve an unrelated issue.  Perhaps this is set too high?

> If you explain your use case a little more maybe we can come up with a better solution.
We're still discussing internally on how much of this we're allowed to share here, but this is what I can give you so far.  Each of these consumers is conceptually performing some failure-prone action.  An action might involve some network latency/other time consuming work and so these actions take different amounts of time to execute.

>  It would be better if you could route the messages 1 to n times to where they need to go rather than relying on kafka with different groups to do it, but I'm not sure what your use case is.

The problem here is that each of these actions needs to maintain an independent offset.

In the ideal case all consumers are "caught up" and are consuming the most up to date data from the topics that they are subscribed to.  In such a case, we could use a single node-rdkafka instance and just perform multiple actions on a batch of messages.  If one of these actions fails though, we don't want to stall processing the next batch of message.  We'd have to create a new subscription for this failing action(so that it could begin to process data independently until it catches up).

You also have a problem that longer running actions on the "up to date" node-rdkafka consumer begin to negatively impact latency of the shorter actions.  Moreover, the algorithm for determining that a previously failing action is now "up-to-date" in terms of committed offset appears non-trivial.

Hopefully that make sense, but I'm happy to clarify further where needed.

> I think there are even places in librdkafka where it uses global locks that will cause lock contention across multiple processes.

Do you know if there a simple way to check that this might be the cause?

**Comment by bobrowadam** [comment]
@csaroff As part of the performance issues you'r having, is there a case in which the consumer stop to consume completely? I'm using a similar configuration and was wondering if you also suffer from this issue.

**Comment by webmakersteve** [comment]
@bobrowadam I believe you're hitting a bug that will be fixed in the next build of librdkafka. I think it is set to be released this or next week.

@csaroff We have a very similar problem that we were trying to solve. We ended up going with `flink` because it was able to create snapshots of messages that are pending processing. A lot of this was to avoid having extra consumers doing nothing but filtering out what they were reading.

I'd be interested to see if the upcoming update to librdkafka also helps with the latency you're seeing in your application, however.

**Comment by csaroff** [comment]
@bobrowadam Sorry, I didn't see this message.  We do see that issue and it's actually pretty common.  We [built a version](https://github.com/rbustami/node-rdkafka/tree/2.3.1) of node-rdkafka using a newer version of librdkafka(although it may be outdated at this point).  The consumer outages did seem to decrease, but they're still there.

@webmakersteve Thanks, I'll check out flink.  We decreased the number of consumers per application instance and the latency issues were drastically reduced

**Comment by bobrowadam** [comment]
@csaroff Thanks for the valuable information! How many consumers are you running on a single instance? we are aiming on using about 6 consumers per instance (CPU core).
@webmakersteve Is there any plan of upgrading librdkafka version any time soon?

**Comment by csaroff** [comment]
@bobrowadam We're at about 6 right now as well.

**Comment by webmakersteve** [comment]
@bobrowadam I've upgrade `librdkafka` since March 14th when I made the last comment, so testing on the most recent `node-rdkafka` comes with the `librdkafka` upgrade.

**Comment by bobrowadam** [comment]
@webmakersteve Oh great. I'll give it a try. BTW, I'm testing a new implementation which uses far less consumers (6 instead of ~100) and so far it works really great with very high throughput while memory and CPU usage dropped drastically and are very stable. Looks promising :)
