### ISSUE TITLE
I/O event loop blocked for 30s 😱 

### ISSUE THREAD

**Issue by oliviertassinari** [Blizzard/node-rdkafka#367]
This issue is part of my effort to make our api kafka fault-tolerant.

Let's say kafka is down. This library will try to fetch the meta data of the cluster
https://github.com/Blizzard/node-rdkafka/blob/f5b9d802e562b47dc9125f262aa2a51fb9f3c71b/lib/client.js#L336
with a 30s timeout
https://github.com/Blizzard/node-rdkafka/blob/22c713b2d9dfbb2b0ef9d42bf2b890c4ed9e4133/src/connection.cc#L207

⚠️ This is blocking the I/O event loop of node ⚠️. For instance, any call to `fs.readFile()` will wait for the node-rdkafka timeout to be reached before returning.

In the following Node timeline, you can see the start and the end of the api request. node-rdkafka is blocking [maxmind](https://www.npmjs.com/package/maxmind) access to the file system, hence delaying the response of the request by 30s.

![capture d ecran 2018-02-28 a 13 24 43](https://user-images.githubusercontent.com/3165635/36787546-cf066b2e-1c8a-11e8-9dee-331877e3185d.png)

I have no experience in writing binding between Node and C++ but maybe libuv can help:
https://nodejs.org/api/addons.html

*(I'm using node v9.5.0)*

**Comment by webmakersteve** [comment]
It's already using `libuv` for that call. If it is blocking `fs.readfile` while doing metadata it is because `libuv` leverages a thread pool per process. The default size of this thread pool is 4 threads, so if you have 3 other busy threads, the read file call is not getting priority. 

Additionally, `librdkafka` will automatically reconnect on failure cases, so you should not have to do the logic yourself - but I'm not sure the use case you're trying for.

If you want to increase the size of the `libuv` threadpool for the process you are using `node-rdkafka` on, you can do so by setting `process.env. UV_THREADPOOL_SIZE` to something greater than 4, which should allow more concurrent asynchronous calls.

**Comment by oliviertassinari** [comment]
Thanks for the answer! It could be linked to size of the `libuv` threadpool. My node process start 4 different producers.
I'm using the stream API. I'm not doing any manual call to `getMetadata`.
I will read more on the `UV_THREADPOOL_SIZE` implications. Either I will try to increase the value or I will make the 4 producers initialization in serie, not in paralell.

**Comment by oliviertassinari** [comment]
Increasing `UV_THREADPOOL_SIZE` is the simplest solution for us.
