### ISSUE TITLE
Consumer streams stop consuming

### ISSUE THREAD

**Issue by bobrowadam** [Blizzard/node-rdkafka#369]
Hi,
I'm using the consumer stream in an ETL service. Currently there are around 60 active consumers and everything works great. Once in a couple of days I notice that one of the streams stop consuming data and I need to manually restart it, yet there isn't any error being emitted regarding this. I Use manual commits and don't wait for the commit callbacks, not sure if that might be related to the issue.
I currently use the `stream.on('error', cb)` for error handling. Is there a better way to get some more data for debugging? 
Thanks.

Here is the consumer configuration:
``` javascript
const hosts = config.kafka.hosts.join(',');

  const globalConfig = {
    'metadata.broker.list': hosts,
    'group.id': groupId,
    'enable.auto.commit': false,
    'offset.store.method': 'broker',
    'partition.assignment.strategy': 'roundrobin',
    'topic.metadata.refresh.interval.ms': 30000,
    'queued.max.messages.kbytes': 10000
  };

  const topicConfig = {
    'auto.offset.reset': 'latest'
  };

  const stream = new Kafka.createReadStream(globalConfig, topicConfig, {
    topics: [topicsRegex],
    waitInterval: 0,
    fetchSize: 1000
  });

  stream.on('error', (err) => {
    if (stream.consumer && stream.consumer._isDisconnecting) {
      logger.error('Error in kafka: Disconnecting in progress');
      return;
    }

    logger.error('Error in kafka ', {
      error_message: err.stack,
      error_code: err.code
    });
  });
```

**Comment by bobrowadam** [comment]
I added some more logs and found that I get lots of the following Error: "Broker transport failure".
It happens on whats seems to be a repetitive periods of time.

**Comment by bobrowadam** [comment]
Might be related to this: https://github.com/Blizzard/node-rdkafka/issues/182

**Comment by erik-stephens** [comment]
> Is there a better way to get some more data for debugging?

You'll want to subscribe to `event.log` event and enable the kinds of msgs that will be emitted via the `debug` librdkafka configuration parameter:

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

It can be really verbose and everything is marked as trace severity.

**Comment by bobrowadam** [comment]
Ok thanks, I'll give it a try.

**Comment by webmakersteve** [comment]
60 consumers?! woah! That's a lot! Happy to know it's working with that many! Let me know if you get any more information with the logs. Usually this is indicative of the fetchers not running because the consumer isn't getting pumped - but the logs will tell us more.

**Comment by bobrowadam** [comment]
* I deployed a version with the 'debug' mode toggled on, and now i'm waiting for that to happen again and see if there is anything interesting in the log. 
* Not sure if related but thought it may worth the try, I found the following error happen from time to time (in stderr):
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/opt/node/v8.9.0/bin/node]
 2: 0x121837c [/opt/node/v8.9.0/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/opt/node/v8.9.0/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/opt/node/v8.9.0/bin/node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [/opt/node/v8.9.0/bin/node]
 6: 0xe1af73 [/opt/node/v8.9.0/bin/node]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/opt/node/v8.9.0/bin/node]
 8: 0x29e3be78463d
```
* And one last thing - You said that 60 consumers are a lot yet we intend to add at least 10 times more. This is an ETL service and each organization has 6 different resources, each of those is being read with a Kafka consumer.  Do you think that node-rdkafka (or librdkafka for that matter) can handle that?

Thanks!

**Comment by webmakersteve** [comment]
Generally you should only have one consumer per kafka cluster per group you need to consume with. If 60 is the minimum you can use to satisfy that requirement, then it's what you need to use. However, I definitely recommend scaling things out so that you have more nodes/processes handling fewer consumers. Whether you static your processes on the same VM or have multiple processes is up to you, but node is single threaded with a threadpool for IO, so generally my formula is `processes = cores - 1` for how many processes to stack on a box for node, with one being okay on a one core box.

Consumers are not inexpensive resources. They do a lot of work to coordinate with other consumers, heartbeat with kafka, fetch partitions, unpack and decompress, etc - so the fewer you have the better.  I would recommend having at least two or three consumers per group (so that means at least 3 partitions as well) so you get high availability, and then scale out by process for the number of consumers you need. Things will definitely run better if you have one consumer per process, but this depends on your hardware constraints.

In your situation where you may need 600 consumers, that means 1200-1800 cpus in an ideal world, and I'm not sure what your hardware situation looks like.

**Comment by bobrowadam** [comment]
Thanks for the thorough answer!
I'll update the thread when I'll have new information to share regarding the issue.

**Comment by bobrowadam** [comment]
One of the consumers stoped again. I went through the debug log and notice that there allot of 'FETCHADD' events. It seems that the topic is being removed and added to and from 'fetch list'. Is that a normal behaviour?
consumer group: 'bp_incidents_some_org'
topic name: correlation.some_org.incident-notifications
Log:
[reporter-debug131.log](https://github.com/Blizzard/node-rdkafka/files/1800381/reporter-debug131.log)

**Comment by csaroff** [comment]
@bobrowadam Were you able to figure out what happened here?

**Comment by bobrowadam** [comment]
@webmakersteve @csaroff We now use much less consumers per CPU core and also made sure we gracefully close the consumers on restart and things works just fine ever since.

**Comment by webmakersteve** [comment]
Going to close this issue. Happy you're having success with a new model!
