### ISSUE TITLE
disconnecting a consumer stream

### ISSUE THREAD

**Issue by bobrowadam** [Blizzard/node-rdkafka#391]
Hey,
Is there a proper way of disconnecting a consumer stream? I tried using `kafkaStream.disconnect()` and it seems to work but I'm not sure how do I get the 'disconnected' event. Tried kafkaStream.on('disconnect', callback) and also kafkaStream.consumer.on('disconnect', callback) yet with no luck. I did notice that there is a `close` function yet this always throws errors which I would like to avoid.
Thanks.

**Comment by JaapRood** [comment]
As far as I'm aware `consumerStream.close(callback)` is the only way to correctly stop a consumer stream. You can pass it either a callback to be notified when it has been stopped, or listen for the `close` event ([a standard event for Node.js streams](https://nodejs.org/api/stream.html#stream_event_close)). There's a good chance the error you're referring to is #384, which got merged but hasn't been released / published to npm yet.

**Comment by JaapRood** [comment]
I've had a bit of a closer look at this, working on graceful shutdown for an app where we use the `KafkaConsumerStream`, showing that I might have bveen wrong about `consumerStream.close(callback)` being the way to stop the stream. In fact, it's only `consumerStream.destroy()` that sets a flag on the stream preventing any future reading. Calling `destroy` calls `close` internally.

If you need to know when the consumerStream was destroyed, you could do so by listening for the `close` event:

```
consumerStream.once('close', onCloseCallback)
consumerStream.destroy()
```

What I'm wondering, though, is why both `close` and `destroy` exist as methods, with different signatures, too.

My best guess is that the idea behind `close` might have been that you can restart it later. However, as far as I'm aware, closing a Node Stream should mean [it should emit no further events and stop computation](https://nodejs.org/api/stream.html#stream_event_close). If you'd want consumption to pause, `stream.pause()` would be used. If that's not possible, creating a new stream would be the way to go. That makes this explanation look less likely.

Maybe @webmakersteve could shed some light on this decision. If it's just some tech debt that still exists just because it's never been cleaned up, I'd be happy to be the one to do so.

**Comment by bobrowadam** [comment]
@JaapRood Thanks. I found that close() works well for me. BTW, pause and resume doesn't seem to work properly. I'm trying to pause a consumerStream, commit an offset, and then resume the stream but it never realy pauses.

**Comment by bobrowadam** [comment]
BTW, I tried to use destroy yet didn't get the 'close' event being emitted.  I'll give it another shot, maybe I did something wrong.

**Comment by webmakersteve** [comment]
@bobrowadam Sorry - was away on vacation. Did you close the issue because you got it to work? 

@JaapRood Close exists just as a method to encapsulate closing if necessary. Destroy exists as the real method that should be called (consider close pseudo-private) that calls close under the hood and flags the stream as destroyed. 

If the docs aren't clear here I think they can be improved, and we can annotate close with a private jsdoc comment so hopefully people know not to use it and to leave it as an internal method.

I used to prefix such methods with an underscore but I'm not sure that's a pattern or an antipattern.

**Comment by bobrowadam** [comment]
@webmakersteve Actually I'm using disconnect() now and it works fine.

**Comment by drvarma** [comment]
@bobrowadam  were you able to make pause and resume work? I'm trying to do something similar, read the message from consumer pause the consumer, commit the message manually and then resume the consumer.

**Comment by bobrowadam** [comment]
@drvarma Unfortunately I haven't yet get to investigate this further. Would appreciate if you could let me know if/when you make it work.

**Comment by Patafix** [comment]
So for a consumer stream we should call, destroy or close ?
Or even stream.consumer.disconnect() ?

**Comment by drvarma** [comment]
I was able to make this work by using the pause(), resume() and disconnect() methods
```
stream.pause(topics)
stream.resume(topics)
stream.consumer.disconnect(()=>{
    console.log('Consumer stream disconnected')
})
```
