### ISSUE TITLE
Rebalance callback not called unless consuming

### ISSUE THREAD

**Issue by JaapRood** [Blizzard/node-rdkafka#400]
Passing a `rebalance_cb` to `KafkaConsumer` allows you to hook into and / or define the rebalancing behaviour. However, it's never triggered unless `consumer.consume` is called. For example, this will never consume any messages: 

```js
var consumer = new Kafka.KafkaConsumer({
  'group.id': 'kafka-testing',
  'metadata.broker.list': 'localhost:9092',
  'rebalance_cb': function(err, assignment) {
    debug('rebalancing')
    if (err.code === Kafka.CODES.ERRORS.ERR__ASSIGN_PARTITIONS) {
      this.assign(assignment)

      setInterval(() => {
        consumer.consume(1)
      }, 45 * 1000)
    } else if (err.code == Kafka.CODES.ERRORS.ERR__REVOKE_PARTITIONS){
      // Same as above
      this.unassign()
    } else {
      // We had a real error
      console.error(err)
    }
  }
})
consumer.connect()

consumer
  .on('ready', function() {
    consumer.subscribe(['example-topic'])
  })
  .on('data', function(data) {
    console.log('Message found!  Contents below.')
    console.log(data.value.toString())

    consumer.commitMessage(data)
  })
  .on('event.log', (data) => {
    console.log(data.message)
  })

```

When looking at the `cgrp` log, you can see that the consumer never gets beyond the state of `wait-assign-rebalance_cb`:

```
[thrd:main]: Group "kafka-testing": delegating assign of 4 partition(s) to application rebalance callback on queue rd_kafka_cgrp_new: new assignment
[thrd:main]: Group "kafka-testing" changed join state wait-sync -> wait-assign-rebalance_cb (v1, state up)
```

## Usecase

Joining the `ConsumerGroup` and waiting to be assigned work before doing any other work, like in stream processing.

## Expected behaviour

To only have to call `consumer.consume` while trying to consume a message, with `rebalance_cb` triggered irrespective of that.

## Workaround

Polling `consumer.consume` manually until we've got assignments from the rebalancing. Additionally, you can use `consumer.pause` and `consumer.resume` to make sure no actual messages are consumed.

## Approach to fix

I'm not that familiar C/C++ and how they bind to Node.js, so the best I could do so far was going through `librdkafka`documentation. In it, you can find how [calling `KafkaConsumer::consume` automatically triggers `RebalanceCb`, `EventCb` and `OffsetCommitCb`](https://docs.confluent.io/2.0.0/clients/librdkafka/classRdKafka_1_1KafkaConsumer.html#a7dc106f1c3b99767a0930a9cf8cabf84). However, the `event_cb` does seem to be triggered even though no `consume` calls are being made, as those would have giving me the debug log above? Perhaps there's some other way to trigger the rebalance callback, rather than consuming?

**Comment by webmakersteve** [comment]
This is a limitation of Kafka in general, and will not be able to be fixed the way you expect, I fear. 

The best way we can accomplish this is by probing with a consume. There is a poll method in the Handle for `librdkafka` but it is not to be called outside of the context of a consume. The `librdkafka` consumer emits all queued events when poll is called, but since that is encapsulated in the consume call, it becomes a side effect that you must be consuming to have information like this.

This is because the Kafka consumer needs to communicate with the broker on an interval, and it communicates through heartbeats. You are only heartbeating when you consume, and you need to heartbeat to find out the information you are asking for.

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-HeartbeatRequest

The response to a heartbeat tells us if the group is in rebalance, which then starts the rebalance callback at the end. And we do not heartbeat until we begin our consumption from Kafka because the consuming and heartbeating are supposed to be linked in some fashion (so hung consumers are evicted from the group).
