### ISSUE TITLE
Kafka Consumer Stream stopped reading messages

### ISSUE THREAD

**Issue by fvcaputo** [Blizzard/node-rdkafka#408]
I have had a Kafka Consumer Stream running for a few weeks now, and only recently for the first time one error surface (twice):
```
Local: Broker transport failure
```
with the data 
```
{code: -195, errno: -195, origin: kafka}
```

Seems like the stream wasnt able to recover in those cases, so we had to manually restart the machine. This led me to create the following check to do it:

```
stream.on('error', (error) => {
       logger.error('Kafka Consumer Stream Error', error);
       if (error.code === kafka.CODES.ERRORS.ERR__TRANSPORT) { // -195 error code
           logger.error('Unable to recover consumer from error, killing process...', error);
           stream.close();
           process.exit(1);
       }
});
```

But this got me wondering if I should be checking for the error code to kill the process, or if in fact when the stream has an `error` event is it always unrecoverable? I started thinking this after checking the consumer example: https://github.com/Blizzard/node-rdkafka/blob/master/examples/consumer.md which actually exits the process on any `error` event. What is the best approach here?

**Comment by webmakersteve** [comment]
If you do not bind an error callback, it should crash the process in any error that is unrecoverable in the stream.

However, I think I would be open to having those errors not kill the stream. I'll make that change.

**Comment by JaapRood** [comment]
@fvcaputo does this happen on trying to make an initial connection to the cluster? Node should exit the process for any stream that doesn't handle the `error` event. As soon as you do, you'll have to exit yourself.

@webmakersteve how were you thinking about recovering from the error? For the initial connection (calling `consumer.connect`) we should retry backing off exponentially, as described in #374. I should still contribute what we've implemented for our project for that (passing `retry` options to `consumer.connect`).

If an error can't be recovered from, the stream _should_ exit and by default so should the process. Otherwise, stream based applications will get stuck, no longer consume messages, but with no way for the outside world to tell.
