### ISSUE TITLE
Questions about topic consumption

### ISSUE THREAD

**Issue by MayhemYDG** [Blizzard/node-rdkafka#43]
Using the standard API,
- Is it possible to know, after calling `consumer.subscribe(topics)`, when the consumer is actually "ready" to consume those topics? Since there is no relevant callback, is manually parsing librdkafka's log events the only way?
- When subscribing to another topic, we have to call `consumer.unsubscribe()` first. Assuming commits are turned off, does that mean we could miss some messages between the call to `unsubscribe()` and the next  call to `subscribe(topics)`?

Thank you.

**Comment by webmakersteve** [comment]
1. Unfortunately `librdkafka` doesn't specifically expose anything that blocks until it is ready. The only thing that sort of gives what you're looking for is the rebalance callback. 

However, in opting into it you are required to do the rebalancing.

If you specify in the global config...
```
{
   rebalance_cb: function(e) {
       if (e.code === 500 /*CODES.REBALANCE.PARTITION_ASSIGNMENT*/) {
        self.assign(e.assignment);
      } else if (e.code === 501 /*CODES.REBALANCE.PARTITION_UNASSIGNMENT*/) {
        self.unassign(e.assignment);
      }
   }
}
```

You can also put relevant code into that callback. The rebalance isn't precisely when it is ready to consume, but it is very close to it.

Additionally, you can use `getAssignments()`. It should return an empty array until it has been assigned partitions, at which point it is about ready to read. You will have to put this in a tail recursive loop and check once you get your initial assignments.

2. I need a little more information to know what you are doing. If you are subscribing to topics, unsubscribing, and then subscribing to the same topics with commits off, as long as it is in the same consumer group, it will start reading from where you committed as long as there is a commit to start from. Otherwise it will use the `auto.offset.reset` value which by default is largest (which means it starts reading from the latest offset once it enters the consumer group.

If you are not using commits and want to ensure you always read from the beginning, you will need to use that configuration value.

Hope that helps.

**Comment by MayhemYDG** [comment]
**Re: kafka ready callback:** I see, maybe this is worth requesting this on the librdkafka issue tracker.
`getAssignments()` threw me off because it doesn't exist, it's `assignments()` instead. Might be good to document it in the README as well.

**Re: unsubscribe:** My use case is as such: the back-end broadcasts messages to front-end servers, which in turn deliver data to the connected clients. Since I don't need to relay broadcasted messages that were sent while a front-end server was offline, as no client would be connected anyway, offsets are disabled and only new messages are read. Every processes are in their own `group.id`, as I need to broadcast all messages.
I use these relevant settings:
```json
  "enable.auto.commit": false,
  "enable.auto.offset.store": false
```
`auto.offset.reset` is not configured, so it defaults to `"largest"`.

So if there is a possibility that a consumer misses messages between the calls to `unsubscribe()` and `subscribe([old topics + new topic])`, I guess my solutions are either:
- enable commits, and read/process old messages anyway,
- or start a separate consumer client.
What do you think? I hope that makes sense.
Obviously subscribing to a new topic without having to unsubscribe first would be ideal, but that doesn't seem possible with librdkafka.

**Comment by edenhill** [comment]
@MayhemYDG If you register a rebalance_cb you also need to call assign() and unassign() for ASSIGNED_PARTITIONS and REVOKED_PARTITIONS respectively. Now, assign() accepts a list of partitions with an optional starting offset (defaults to INVALID offset which causes it read offsets from the broker or auto.offset.rewset).
What you could do is save your current position for your consumed partitions when you get the REVOKED event by calling position(), and then updating the offsets of all matching partitions in the next ASSIGNED event you get.
This way you wouldnt miss any messages when your subscription set changes.

As a simplification; if your partition count is fixed for the subscribed topics you can skip the subscribe() step and simply call assign() directly, you will need to know the number of partitions per topic though (see metadata()). In this case there will be no consumer group join (which you dont need anyway it seems)

**Comment by MayhemYDG** [comment]
Thanks for the tip @edenhill!
Looks like `assign()` is the solution I need, I'm not familiar with it so I'll have to look into it.

**Comment by webmakersteve** [comment]
I think @edenhill's solution is the best here.

However, `position` is not currently implemented. Actually working on that now so hopefully will be available soon.

You can keep track of the position by reading the offset on the messages for now, then start from the latest one read.

**Comment by webmakersteve** [comment]
Added in mega PR #42
