### ISSUE TITLE
Messages lost during rebalance.

### ISSUE THREAD

**Issue by jesse-localz** [Blizzard/node-rdkafka#437]
When attempting to produce and consume messages on the same thread for the same topic, there appears to be dropped messages.  
If you produce and consume on a thread start you can see the behaviour. The consumer will connect and subsequently undergo a rebalance. If the `node-rdkafak` producer connects and publishes a message before the consumer group is stabilised the messages will be lost.
It seems as if this is the intended functionality?

**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: OSX, RHEL
 - Node Version [e.g. 8.2.1]: 8/9/10
 - NPM Version [e.g. 5.4.2]:
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: gcc
 - node-rdkafka version [e.g. 2.3.3]: 2.3.1

**node-rdkafka Configuration Settings**
I have attempted to resolve this issue by following the advice [here](https://github.com/Blizzard/node-rdkafka/issues/435) and [here](https://github.com/Blizzard/node-rdkafka/issues/108). Unfortunately setting `auto.commit.reset = earliest` does not seem to resolve the issue.

**Comment by webmakersteve** [comment]
Can you go onto your Kafka broker and see if it has an entry for the group you are using to consume with? When you first connect to Kafka and do not have offsets, you will need to wait for the rebalancer to finish doing its work. At that point it will have offsets to consume from.

If you crash after that before you have done your first commit, the group will still not exist as far as Kafka is concerned (because it uses offsets to track groups). 

The offset reset parameter is just supposed to instruct the consumer on what to do when there are no offsets found for the group. Earliest -should- make it so you get all messages. But it looks like that is not the behavior you are seeing.

It would help to have a case where this can be reproduced (like a container, for example). If it all possible.

**Comment by rclayton-the-terrible** [comment]
I'm using `auto.commit.reset = beginning` and it's working well for me.
