### ISSUE TITLE
Unable to consume messages

### ISSUE THREAD

**Issue by mimaison** [Blizzard/node-rdkafka#44]
Following your latest updates, we are not able to consume messages anymore. 

This is the sample we used:
```
var Kafka = require('../');

var topic = 'testtopic';

var consumer = new Kafka.KafkaConsumer({
  'debug': 'all',
  'metadata.broker.list': 'localhost:9092',
  'group.id': 'node-rdkafka-consumer' + new Date().getTime(),
  'enable.auto.commit': false
}, {
  'auto.offset.reset': 'latest'
});

// Flowing mode
consumer.connect();

consumer.on('event.log', function(log) {
  console.log(log);
});

consumer.on('data', function(m) {
  console.log('Received a message:');
  console.log('  message: ' + m.payload.toString());
  console.log('  key: ' + m.key);
  console.log('  topic: ' + m.topic);
  console.log('  offset: ' + m.offset);
  console.log('  partition: ' + m.partition);
});

consumer.on('ready', function() {
    console.log('ready');
    consumer.consume([topic]);
});
```

We've tried adding calls to subscribe(), adding a callback to consume(), nothing seems to work.

Running with debug set to all, we can see it's actually fetching messages but the 'data' callback is never invoked.

```
{ severity: 7,
  fac: 'SEND',
  message: 'mickael-ThinkPad-W530:9092/0: Sent FetchRequest (v1, 68 bytes @ 0, CorrId 46)' }
{ severity: 7,
  fac: 'RECV',
  message: 'mickael-ThinkPad-W530:9092/0: Received FetchResponse (v1, 351 bytes, CorrId 46, rtt 91.23ms)' }
{ severity: 7,
  fac: 'FETCH',
  message: 'mickael-ThinkPad-W530:9092/0: Topic testtopic [0] MessageSet size 310, error "Success", MaxOffset 20, Ver 3/3' }
{ severity: 7,
  fac: 'CONSUME',
  message: 'mickael-ThinkPad-W530:9092/0: Enqueue 10 messages on testtopic [0] fetch queue (qlen 1, v3)' }
{ severity: 7,
  fac: 'FETCH',
  message: 'mickael-ThinkPad-W530:9092/0: Fetch reply: Success' }
```

**Comment by webmakersteve** [comment]
I just pushed a fix for this. The subscribe refactor wasn't updated in the `_consumeLoop` method. This should be adjusted.

FYI - It is now `m.value` not `m.payload`. I will update all the documentation before I make the next release

**Comment by edoardocomar** [comment]
Thanks, @webmakersteve  - fix verified. 
Also consumer.disconnect() works now :-)

should we still use
`consumer.consume([topic]);`
rather than
`consumer.subsrcibe` 
?

**Comment by webmakersteve** [comment]
`consumer.consume([topic])` will run a background thread that consumes as fast as kafka can give it messages. If you don't need control over the rate of messages, this is probably a good solution because there is less back and forth between v8 and the library.

That method implicitly calls subscribe for you so you shouldn't call subscribe in addition to using it. Subscribe just tells kafka what topics you're interested in, but since you are providing those as a parameter, it is done automatically.

The other options are to manually subscribe and fetch `x` messages at a time, fetch 1 message at a time, or use a stream that manages how many to fetch for you. It all depends on what you're trying to do with the data and if you're concerned about the infinite concurrency problem.

Hope that helps! And glad disconnect is working! :)
