### ISSUE TITLE
Cursor state stored in external store

### ISSUE THREAD

**Issue by thebigredgeek** [Blizzard/node-rdkafka#453]
Is there an easy way with this lib to store and revive cursor state into an external store (pick your favorite database) in a way that works consistently across connection issues, rebalances, etc?

With my use case, in particular, I'd love to be able to persist `topic.id:partition.id:consumer_group.id = offset` in postgres within the same transaction that I use to process a message and apply changes.  This way I never accidentally replay changes if, say, a commit fails

**Comment by webmakersteve** [comment]
I assume you want to try to do exactly once semantics? Your offsets will still need to be stored in Kafka, but what you will want to do is wrap your insert into an atomic transaction that uses your offsets, topic, partition etc. as one of the inserts (ensuring it cannot overwrite existing data).

So, pick your favorite database:

```
START TRANSACTION;
INSERT INTO `my_data` (col) VALUES ('value');
INSERT INTO `committed_offsets` (topic, partition, offset) VALUES ($topic, $partition, $offset);
COMMIT;
```

You will need to ensure that the second insert fails if one exists already. You can do this using a UNIQUE key.

```
CREATE TABLE committed_offsets (
    offset LONG,
    partition INT,
    topic VARCHAR(255)
    PRIMARY KEY (topic, partition, offset)
);
```

This means when you try to insert the offsets in the transaction from the message you read, it will fail to do so because the offset has been committed already.

So now, in your code:

```
database.write(kafkaMetadata, dataToWrite, (err) => {
  if (err.code == 'PRIMARY_KEY_VIOLATION') {
    // This means the record exists already and we do not want to put it in again
  } else if (err) {
    throw err; // ?
  }

  // If we got here it means the record surely exists in the database. Either it was there before, or it was  
  // updated
  consumer.commitMessage(kafkaMetadata);
});
```

**Comment by thebigredgeek** [comment]
@webmakersteve thanks for the reply!  Yes, exactly once.  Your description is super helpful.  My main unknown here is about how to actually implement this with the interface that `node-rdkafka` provides in a way that handles reconnections, rebalances, pulling existing cursor state as soon as the process revives, etc.

**Comment by thebigredgeek** [comment]
Also, do you feel like it's worth keeping the consumer group id as part of the PK in Postgres?  It seems like that would be necessary to keep offsets unique to a consumer group, since multiple consumer groups can consume from the same partition

**Comment by thebigredgeek** [comment]
Bump

**Comment by webmakersteve** [comment]
@thebigredgeek  I would definitely recommend keeping the consumer group in whatever you are committing to, so that you can replay data by changing that group transparently as you would if offsets were being managed elsewhere.

I think the way I described should get you where you need to be. You still want to store offsets in Kafka, but you just store the state of that message in your database that is the destination. So I don't see that you need to hook into any callbacks or anything to provide or get information. 

Reconnections and rebalances should be handled under the hood so you should not have to engineer for those problems when using node-rdkafka.

Hope that helps.

**Comment by webmakersteve** [comment]
You can commit in the rebalance callback to ensure when you have yielded your partition to potentially another consumer node, that it will start in that position. Does that answer the question?
