### ISSUE TITLE
KafkaConsumer~consume and KafkaConsumerConsumeNum::KafkaConsumerConsumeNum have different interpretations of the timeout/partition end

### ISSUE THREAD

**Issue by ankon** [Blizzard/node-rdkafka#467]
In our environment we have very few messages per second coming into our topics, and we want to process these as quickly as we can. 

We noticed a considerable latency of 1s minimally (never less than that), and up to a few seconds when using node-rdkafka. Testing with standard kafka and rdkafka performance tools didn't exhibit any issues and showed us that the cluster and the client are capable of easily handling the amount of messages in our desired latency. Further instrumentation of our own producer code also showed that the latencies of producing messages (time between us handing the message off and receiving the delivery report for that message) where acceptable.

We then tested with a combination of the `rdkafka_performance` tool as producer of messages that would be acceptable to our system, and measured the latency there: We still observed the 1s latency. In one instance I changed the rate of producing messages to 1/s, and actually got to a state where our consumer would not process any message for multiple seconds, and kafka would report the lag on the consumer group to increase continuously.

Enabling suitable debug logs of rdkafka (aka "all" :D) showed that while rdkafka reports it is fetching the new messages, it never seemed to hand them over to us.

Reading through the code I foundt that the problem is in KafkaConsumerConsumeNum::KafkaConsumerConsumeNum: When it reaches the end of the partition it simply retries rather than aborting, and for each retry it applies the timeout again. In the worst case this leads to the situation that it reads one message, hits the end-of-partition, retries reading with a timeout of 1s, and just before the timeout ends receives another message. As long as the number of messages doesn't exceed the requested maximum it will then go on, ending in a potentially "infinite" loop if the producer just sends out a slow stream of messages.

In our case we call consume with a size of 1000, and a timeout of 1000, the idea being to get "a lot of messages" when there are plenty, and avoiding busy loops when there are no messages.

KafkaConsumer~consume(sz, cb) states:
> This will keep going until it gets ERR__PARTITION_EOF or ERR__TIMED_OUT
> so the array may not be the same size you ask for. The size is advisory,
> but we will not exceed it.

This sounded reasonable for me, I assumed that it would get us whatever it has in big batches (sz=1000), but would quickly stop when the partition has reached the end.

I've now changed the timeout to 10ms, which gets us nice latencies, but I think something needs to be done in KafkaConsumerConsumeNum:
1. Fix the handling of the partition end to actually abort (matching the description of the caller), and/or
2. Treat the timeout as timeout for the operation, not as timeout for a single fetch, and/or
3. Somehow fix the documentation so it is clear that calling consume(sz) with a timeout of t could take up to t*sz ms to complete. :)

**Environment Information**
 - node-rdkafka version: 2.3.4

**node-rdkafka Configuration Settings**
* consume timeout is set to 1000 (ms, the default as per https://github.com/Blizzard/node-rdkafka/blob/5e971743047c373aaf046db15528ff6b818eb281/lib/kafka-consumer.js#L123)
* consumer global options: 
   ```json
   {
     "debug":"broker,cgrp,topic",
     "enable.auto.commit":false,
     "log.connection.close":false,
     "queue.buffering.max.ms":10,
     "queued.max.messages.kbytes":10240,
     "session.timeout.ms":6000,
     "socket.blocking.max.ms":100,
     "socket.keepalive.enable":true,
     "metadata.broker.list":["kafka:9092"],
     "statistics.interval.ms":30000,
     "group.id":"@collaborne/polaris-service/polaris-service-489987766-9zl60/9e772105-d823-40b6-ae90-4ae1c88131a9",
     "offset_commit_cb":true
   }
   ```
   (auto-commit is disabled as we're committing manually after each batch, broker points to a DNS name that rounds-robins over a 3-kafka/3-zookeeper cluster)
* consumer topic options
   ```json
   {
     "auto.offset.reset":"latest"
   }
   ```

**Comment by ankon** [comment]
One thing I'm still trying to understand whether this is "reasonable" or "confusing" is the fact that the consume method would wait _at least_ for one timeout even when a message was available before returning when the topic is not receiving messages, which explained our minimum latency of 1s.

**Comment by webmakersteve** [comment]
Pretty sure it used to stop at EOF and then it was requested that I change it because the behavior was confusing 😛 

I would prefer to get the library back to a true 1:1 mapping in the low level API, and that's what I'm going to do to get around this. Basically this means errors will be transparently surfaced to the user in the low level API, and it is up to you to handle them (through retries, etc.) if necessary. 

I think that will solve this problem.

**Comment by Tapppi** [comment]
I agree completely with the sentiment here, `KafkaConsumer~consume()` contract is broken by `KafkaConsumerConsumeNum`. The problem is, that this pretty much breaks any low-latency application using `node-rdkafka` and trying to optimise for situations where it is waiting for new messages without hogging all cpu by lowering consume timeout and constantly hammering `consume`.

Under the hood the code path eventually calls librdkafka's method [`rd_kafka_consumer_poll`](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2903) ([docs](https://docs.confluent.io/2.0.0/clients/librdkafka/rdkafka_8h.html#a65cc6cb9bd72c4084f074af0361ceddf)). I'm not sure whether that function returns `ERR__PARTITION_EOF` when **any** partition hits end. If so, there might be messages from other partitions waiting, and there doesn't seem to be way of knowing other than calling `KafkaConsumer::Consume` again. I think that invalidates solution 1, as it will cause smaller than intended batches when it doesn't need to. 

Solution 2 is interesting for many reasons, and would be fairly trivial to implement. It fixes the problem of slowly trickling in messages taking max `sz*timeout` to return, but it alone will still cause the consume to take **at least** `timeout`, even when all partitions have been drained. I.e. it will still take at least `timeout` for you to get that one/two messages that come in every second even if it cannot take multiple seconds.

### Solution 4

I propose a new solution that cuts down on unnecessary time waiting for slowly trickling in messages when partition queues have been drained. Alone this solution only helps when partitions actually drain (`ERR__PARTITION_EOF`), but combined with Solution 2 (having a timeout for the whole consume instead of single message consumes) this would bound the consume to `1 < X < (timeout + time of consuming queued messages until batch full)` running time. The running time would be very small only when there are only a few messages ready to be consumed and a partition EOF has been hit. If there are no messages at all, it would still wait for at least `timeout`.

I wonder if setting the timeout to 1 (or 0?) when a `ERR__PARTITION_EOF` happens would allow fetching "ready-for-consumption" messages, but return immediately if no such messages are queued. This would ensure that the consumer doesn't wait for new messages slowly trickling in in a loop when it has drained an assigned topic partition. The consumer would only wait as long as it takes for either:
* a batch to be complete
or 
* all immediately consumable messages to collect after a partition hits EOF

> I would prefer to get the library back to a true 1:1 mapping in the low level API, and that's what I'm going to do to get around this. Basically this means errors will be transparently surfaced to the user in the low level API, and it is up to you to handle them (through retries, etc.) if necessary.


Until that (breaking change?) happens, I have laid out this change in https://github.com/Blizzard/node-rdkafka/pull/469.

I would also support implementing Solution 2 as an option similar to `consumer~setDefaultConsumeTimeout`, as these two changes would allow one to reliably bound the consumption time while also tuning batching.

**Comment by ankon** [comment]
> The consumer would only wait as long as it takes for either:
> 
> * a batch to be complete
> or
> * all immediately consumable messages to collect after a partition hits EOF

I would say that this would match my "expectations" in terms of behavior quite nicely. I would like to avoid doing consume() with a low timeout, as that will increase the required CPU resources.
