### ISSUE TITLE
Handling of subscribe to non-existant or non-authorized topics

### ISSUE THREAD

**Issue by tvainika** [Blizzard/node-rdkafka#479]
My system had a configuration issue of subscribing to wrong non-existant on consumer mode. There was no error produced by node-rdkafka against my expectations.

There was no much documentation either on expected behavior of subscribe to either non-existant or non-authorized topics.

Current behavior seems to be:
1. Non-existant topics are just silently subscribed to, but no messages will appear.to be consumed.
2. Non-authorized topics throw error asynchronously. The topic seems to be still listed as subscribed (`KafkaConsumer.subscription()`) which I believe is just fine, but still means that next consume attempt may throw the error again.

I quickly looked at kafkacat source code as kafkacat detects both cases nicely. It seems to check for non-existant topics from metadata, and stops at first error of topic authorization failed.

I'd expect KafkaConsumer to throw an error if trying to subscribe to non-existant topic. I'd love to find something about non-authorized topics from the documentation.

**Comment by linusred** [comment]
This is intentional since a kafka client can be started before the topic is created ( orthrough other means).

This is also being tracked in librdkafka, although I wouldn't expect a resolution anytime soon.
https://github.com/edenhill/librdkafka/issues/1201

If you want your application to do something if a topic isn't available, currently the best solution is for you to use the metadata to detect if the topic is present, and if it's not log/alert/doyourthing.

https://github.com/Blizzard/node-rdkafka#metadata
