### ISSUE TITLE
how to offset to 0 and start reading from scratch?

### ISSUE THREAD

**Issue by esuarezz** [Blizzard/node-rdkafka#495]
I want to consume from zero if the server gets disconnected and I dont find here how to manage it

**Comment by JaapRood** [comment]
Using `consumer.seek` you can control the current position in the log that you're consuming. You can either use a absolute offset, or a logical one like 'earliest' or 'beginning'. With the latter, the library will handle looking up what the latest available offset is, as this might not be `0` anymore, due to Kafka garbage collecting either based on time or using compaction.
