### ISSUE TITLE
Version 2.4.2 causes Segmentation fault on Heroku Servers

### ISSUE THREAD

**Issue by DServy** [Blizzard/node-rdkafka#506]
**Environment Information**
 - OS: Heroku basic dynos (backed by AWS.) 
 - Node Version: 8.X and 10.X
 - NPM Version: 6.1.X
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: No idea (heroku set)
 - node-rdkafka version [e.g. 2.3.3]: 2.4.2

**Steps to Reproduce**
build a package with the following version of Librdkafka as a buildpack
https://github.com/SalesforceCloudServices/heroku-buildpack-librdkafka

attempt to produce

get the following message in logs
`Segmentation Fault`
(dyno restarts)

**Additional context**

Reaching out to heroku to try to find out more info on the sigfault in general.

Doesn't affect older versions

Happens on production

**Comment by sprijk** [comment]
Confirmed for Node.js 8.14.x

8.10.x however works

**Comment by jesse-localz** [comment]
I am also seeing this issue with node 8.14.
Specifics:
Environment Information

- OS: debian slim stretch
- Node Version: 8.14.X
- NPM Version: 6.1.X
- C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
- node-rdkafka version [e.g. 2.3.3]: 2.3.1

**Comment by JaapRood** [comment]
I've experimented with various combinations and can report that I only see the segfault in `node@^8.14.x` (so not in node v10) and combined with the Heroku-18 stack (based on Ubuntu 18.04). Because of #566, running against node v10 isn't an option right now if you're running with SSL (which you probably should be in production) and most likely won't be until `librdkafka@1.0.0` (which brings OpenSSL v1.1.x support). 

While you could run against node v8.10.x, I'd recommend running your app on heroku's `heroku-16` stack, which is based on Ubuntu 16.04 and in LTS until mid 2021 (beyond that of node v8), which hasn't produced the segmentation fault for me as of yet. That gives you a combination of 2 recently supported versions, rather than being stuck on an unpatched version of node.
