### ISSUE TITLE
supported kafka v2.0?

### ISSUE THREAD

**Issue by lvgithub** [Blizzard/node-rdkafka#509]
supported kafka v2.0?
 
on ready event sucess ,but does't on data evnet

**Comment by rclayton-the-terrible** [comment]
Yes.  I'm using Kafka v2 via the Confluent Enterprise Kafka (5.0.0) distribution.

One mistake I made, which was causing my consumer to not receive data on startup, was to specify the `auto.offset.reset` property:

```javascript
const config = Object.assign({}, this.options.connection, {
  'client.id': this.clientId,
  'group.id': this.options.domain,
  'rebalance_cb': true,
})

const topicConfig = {
  'auto.offset.reset': 'beginning',
}

this.consumer = new KafkaConsumer(config, topicConfig)
```

**Comment by lvgithub** [comment]
thanks

**Comment by noderat** [comment]
Since I was investigating for potential Kafka 2.0 related incompatibility issues and came across this thread I'd like to point out for others doing the same:

* Having to set "auto.offset.reset" for a consumer group that doesn't already exist is not new to Kafka 2.0
* This issue is misconfiguration not incompatibility.

@ivgithub if that resolved your issue please make a comment saying so.
