### ISSUE TITLE
Memory leak Producer with high rate

### ISSUE THREAD

**Issue by micaelmbagira** [Blizzard/node-rdkafka#622]
If I produce data at a very high rate (every 10ms) using the standard Producer API, I end up with the memory increasing really fast and eventually the process would crash with the error `Error: Local: Queue full`.

However, if I use the `createWriteStream` API, it's fine.

The issue might be related to [this one](https://github.com/Blizzard/node-rdkafka/issues/438) 

**Environment Information**
 - Docker (Alpine)
 - node-rdkafka ^2.6.1

**Steps to Reproduce**

```js
// This code leaks very quick
const producer = new Producer({
  'metadata.broker.list': 'kafka:29092'
});

producer.connect();
  
producer.on('ready', () => {
  // this simulator emits data every 10ms 
  simulator().subscribe(data => {
     producer.produce(
       'xxx',
       null,
       Buffer.from(JSON.stringify(data))
     );
  });
});

// This code doesn't
const stream = createWriteStream({
  'metadata.broker.list': 'kafka:29092'
}, {}, {
  topic: 'xxx'
});
  
simulator().subscribe(data => {
  const queuedSuccess = stream.write(Buffer.from(JSON.stringify(data)));
  if (!queuedSuccess) {
    console.log('Too many messages in our queue already');
  }
});
```

**Comment by micaelmbagira** [comment]
Ok, after reading this one https://github.com/Blizzard/node-rdkafka/issues/308 I understood I need to poll manually 😃 

Then, I am wondering, is there a reason why I should use the standard API vs the Stream API? In the documentation it says 
> The Standard API is more performant, particularly when handling high volumes of messages
Is that really the case and why?

**Comment by codeburke** [comment]
To each his own on Standard vs Stream. The Standard API is the lowest level Node API to the `librdkafka` C API, which means it obviously does not have the overhead of the Node Stream implementation. In fact, if you look under the covers the Stream code is just the standard producer/consumer wired up to the Node Stream API. That said, I'm a big fan of the Stream interface since it plays very nicely into standard functional stream processing mechanics that you see in our stream processing systems like KStream, Samza, etc.
