### ISSUE TITLE
Producer e2e tests, deadlock after using Topic object in produce

### ISSUE THREAD

**Issue by mimaison** [Blizzard/node-rdkafka#64]
As discussed in https://github.com/Blizzard/node-rdkafka/pull/62#issuecomment-261219970, if the testcase called `should produce a message to a Topic object` is executed before `should get 100% deliverability`, the latter testcase hangs.
If in the first testcase we change the topic object to be a string, then the second testcase doesn't hang.

We've also managed to reproduce this issue in a small testcase script (see enclosed). It's basically the same logic from the tests but inlined and without any mocha deps to be run with node directly. Note that if we enable DEBUG the script doesn't hang. Like in the e2e tests, changing the topic object to a string makes it pass.

[testcase.txt](https://github.com/Blizzard/node-rdkafka/files/597320/testcase.txt)

**Comment by webmakersteve** [comment]
Pretty sure this is because an issue with garbage collection. I'm not sure the best way to handle it currently (perhaps it is making the c++ side of things do the management of topics), but when you instantiate a topic and then try to disconnect, the producer refuses to let go until the topic has been deallocated...

It doesn't get deallocated because node still has a handle to it, and then they both just sit there and wait. 

I think I may need to refactor it to take a raw object instead of a wrapped one so it can still deallocated memory in C++ nonwithstanding of the node scoping. But I will see if there's a workaround for the time being,

**Comment by webmakersteve** [comment]
Changes in #127 should fix this issue.
