### ISSUE TITLE
Producer delivery reports - cannot figure out which message they relate to 

### ISSUE THREAD

**Issue by edoardocomar** [Blizzard/node-rdkafka#70]
The current delivery-report object contains key, offset, topic ... but this is not enough to figure out about which produced message they refer to.
Unless you wait for every single report after sending a single message.

Looking under the covers, node-rdkafka is using the full dr_cb_msg librdkafka callback, but does not put the message payload in the delivery report.

Investigated with @mimaison

**Comment by mimaison** [comment]
In addition, if we get an error in the delivery report, currently we only emit an error event.

I think it would be better to call the delivery report callback (in addition of error) and pass in both the error and the report, so the user can check the error and have the message. That would make it easier to find which produce() has failed and having the message we can retry if we want.

We'll send a PR tomorrow, so it's a bit easier to discuss the changes we're suggesting

**Comment by webmakersteve** [comment]
A little unclear on the suggestion. But I'll wait until you propose a PR.

I'm not the biggest fan of transmitting the entire payload to the delivery report. This is not an environment where I have flexibility in using shared memory, because they need to be attached to handles that exist in potentially independent scopes. This means I would need to do another memory copy for potentially kilobytes (or more?) of data every time a delivery report comes in. That's why I elected not to do this.

There is another not implemented way of identifying which message a delivery report belongs to: `msg_opaque`. I would be more inclined to add support for that feature in case you need to know which message was delivered.
