### ISSUE TITLE
consumer can't catch up with new data.

### ISSUE THREAD

**Issue by yuby** [Blizzard/node-rdkafka#710]
I have 32 partitions and one topic. I try to consume real-time while producing a lot of log data.
The first seconds of data seemed fine. But as time goes by, they can't catch up with new produced data.
Can i solve this problem through the node cluster? Or is there another way? Or is there way to force update to current highest offset??

```
const Kafka = require('node-rdkafka');

const broker = 'broker';
const topic = 'topic';

module.exports = ({ id, dataHandler }) => {
  const consumerConfig = {
    'group.id': `group-${id}}`,
    'metadata.broker.list': broker,
    'socket.keepalive.enable': true,
    'enable.auto.commit': true,
    'offset.store.method': 'broker',
    'partition.assignment.strategy': 'roundrobin',
    'topic.metadata.refresh.interval.ms': 6000,
    'queued.min.messages': 1000,
  };
  const topicConfig = {
    'auto.offset.reset': 'latest',
  };

  const stream = new Kafka.createReadStream(consumerConfig, topicConfig, {
    topics: [topic],
    waitInterval: 0,
  });

  const { consumer } = stream;

  const disconnect = async () => {
    consumer.disconnect();
    stream.pause();
    stream.close();

    stream.once('close', () => console.log('close'));
  };

  async function getMetadata(_client) {
    return new Promise((resolve, reject) => {
      _client.getMetadata(null, (err, metadata) => {
        if (err) {
          reject(err);
        } else {
          resolve(metadata);
        }
      });
    });
  }

  function getOffset(client, _topic, partition) {
    const partitionWatermark = client.getWatermarkOffsets(_topic, partition);

    let offset = partitionWatermark.highOffset;

    if (offset > 0) {
      offset -= 1;
      offset = Math.max(offset, -1);
    }
    return offset;
  }

  consumer
    .on('subscribed', async () => {
      const client = stream.consumer;
      const metadata = await getMetadata(client);
      const topicPartitions = [];
      const partitionIDs = [];

      console.log('subscribed');

      const latestStart = () => {
        metadata.topics.forEach((_topic) => {
          const { name, partitions } = _topic;

          if (name === topic) {
            partitionIDs.push(...partitions.map((tp) => tp.id));
            topicPartitions.push(...partitions.map((tp) => (
              {
                partition: tp.id,
                topic: name,
                offset: getOffset(client, _topic.name, tp.id),
              }
            )));
          }
        });

        client.assign(topicPartitions);
      };

      setTimeout(latestStart, 1000);
    });

  stream
    .on('error', (err) => { console.error('Client error', err); })

  stream
    .on('data', (message) => {
      dataHandler(message.value.toString());
    });

  process.on('SIGTERM', async () => {
    disconnect();
  });
  process.on('SIGINT', async () => {
    disconnect();
  });
};

```

**Comment by codeburke** [comment]
A single threaded Node process can only handle so much data processing. So the throughput will be very affected by the amount of processing in `dataHandler` for high volume topic/partitions. Since this is a 32 partition topic the easiest way to get more performance is to spin up other instances of the app so the load is distributed to all the instances in the same Consumer Group. 

Without knowing more about the type of processing you are doing or the rate of messages being published it is hard to pinpoint exactly what needs to be done to get you caught up to realtime.

Just as a note for comparison, at my company we are seeing ~2k messages/sec per instance of an app that is taking 2-8KB Avro messages, converting to JSON, doing some quick manipulations and republishing in Avro format. When I pulled a CPU profile the JSON operations and Avro serialization/deserialization are the biggest CPU hogs. Each instances gets a single CPU core and 384MB of RAM. All of that is using the ConsumerStream API like you are.

**Comment by yuby** [comment]
My application has one master and eight cluster structures.

```

if (cluser.isMaster) {
	os.cpus().forEach(() => {
		cluster.fork();
	});

} else {
	// consumer code here
}


```

as I know, if i have 32 partitions, i should have 32 consumers.

So I'm creating eight clusters, and I'm creating four consumers internally, and I'm operating a total of 32 consumers. And the data received is stored in redis.

and this dataHandler is just to save data in redis.

```
...
redis.zadd(`key`, Date.now(), JSON.stringify(data));
...
```
Kafka producer produces around ~100k messages/sec.

Do you think node.js is not enough to handler this amount data?

**Comment by codeburke** [comment]
It is entirely possible that you don't have enough horsepower. We over-indexed a bit and use 120 partitions for a topic that gets 2-20k events/sec @ 2-8KB / event. As I mentioned previously, depending on the size of the JSON data it can have a pretty significant affect on overall throughput since it is a synchronous operation that blocks the event loop.

Do you have any metrics like avg, P90, P99 milliseconds it takes to process an event? That timing along with the 32 partitions should tell you if you are scaled out enough to handle the load.

**Comment by yuby** [comment]
@codeburke I have tried to find a solution so far. As you said, the size of our JSON data looks big. It seems that a lot of resources are used to convert from string to JOSN. I will try to solve this using Promise, Worker.. etc. And also I try to do the same thing by changing the language to GO or java. Thank you for your help.
