### ISSUE TITLE
Consumer timeout issue?

### ISSUE THREAD

**Issue by keith-chew** [Blizzard/node-rdkafka#716]
**Environment Information**
 - OS [Windows]: 
 - Node Version [10.16.3]:
 - NPM Version [6.9.0]:
 - C++ Toolchain [Visual Studio]:
 - node-rdkafka version [2.7.4]:

Hi

I reported an issue at:
https://github.com/edenhill/librdkafka/issues/2634

It appears that this could be a bug with node-rdkafka. Basically, the consume(number, cb) method takes longer than the timeout specified with setDefaultConsumeTimeout() when the number of messages is less than the count provided.

Please advise.

**Comment by codeburke** [comment]
I think I found the problem. The issue is that the node-rdkafka consumer thread is actually plucking the messages from the `librdkafka` C++ API one at a time. Each call to that C++ `Consume()` [[code](https://github.com/Blizzard/node-rdkafka/blob/master/src/kafka-consumer.cc#L414-L435)] is given up to `setDefaultConsumeTimeout()` to complete instead of the entire batch being timed up to `setDefaultConsumeTimeout()` [[code](https://github.com/Blizzard/node-rdkafka/blob/master/src/workers.cc#L528-L530)]. I assume that normally this isn't a problem since `librdkafka` aggressively caches, but it does seem like this issue could lead to some problems if the `librdkafka` cache is configured to be very small while the `consume(num)` requests a large number of messages with a small timeout. 

So the options here are
1. Update the documentation to indicate that the max timeout for a `consume(num)` call is `num * value of setDefaultConsumeTimeout()`.
2. Update the documentation and code to actually support a Node `consume()` timeout instead of just the underlying C++ `Consume()` call. This should be in a new minor version release `2.8.0`.  

My gut says to go with the second option, but I'm open to other's opinions on how invasive that might actually be. @webmakersteve @iradul

**Comment by keith-chew** [comment]
My apologies for not updating this issue, only updated in:
https://github.com/edenhill/librdkafka/issues/2634

I have created a fork which adds a new parameter "total timeout":
https://github.com/edenhill/librdkafka/issues/2634

Now the consume will return a maximum "total timeout" + "consume timeout"

**Comment by keith-chew** [comment]
Yes, this issue only shows up when you configure a large number (in our case 1200) and can experience long delays in a low throughput time, eg off peak hours. We have seen lags of up to 18s but with total timeout, it now returns after 1s.

**Comment by codeburke** [comment]
That’s great. Can you open a PR so we can work on getting that merged in?

**Comment by keith-chew** [comment]
PR here:
https://github.com/Blizzard/node-rdkafka/pull/727

**Comment by keith-chew** [comment]
Fixed cpplint errors and replaced PR with new one:
https://github.com/Blizzard/node-rdkafka/pull/728
