### ISSUE TITLE
 When passing multiple topics to the consumer, the first picked topic is consumed completely and then only remaining topics are processed in batches.

### ISSUE THREAD

**Issue by sanketdhoble** [Blizzard/node-rdkafka#719]
**Environment Information** 
 - Node Version [e.g. 8.4.11]:
 - node-rdkafka version: 0.10.0
Using single node process, single consumer & multiple topics.

**node-rdkafka Configuration Settings**
```
        this.producer = new Kafka.Producer({
            'client.id':'rdkafka-scheduler-client',
            'group.id': 'rdkafka-scheduler-group',
            'metadata.broker.list': config.brokerList,
            'compression.codec': 'none',
            'retry.backoff.ms': 100,
            'message.send.max.retries': 2,
            'socket.keepalive.enable': true,
            'queue.buffering.max.messages': 100000,
            'queue.buffering.max.ms': 1000,
            'batch.num.messages': 1000000,
            'delivery.report.only.error': true,
            'dr_cb': true,
            'dr_msg_cb': false
        }, {
                'produce.offset.report': true,
                'request.required.acks': 0
            });

        this.producer.connect();

        this.producer.setPollInterval(config.producerPollIntervalMs || 0); 

```
**Additional context**
Issue: Passing multiple topics to the consumer, the first topic is picked and it is finished.
Then onwards remaining topics are juggled in batches of ~2k msgs per topic.
Why is the first topic is picked and consumed completely and then only all other topics are picked in batches? 

**Steps to Reproduce**
1) Inside a for loop, send 100k msgs to topic-1, next 100k msgs to topic-2, and so on till topic-n
consumer starts picking topic-1 messages only till they are totally consumer, then only other topics are picked in batches which are expected.

> Msg count till now, topicwise msg count
=> 66080, { 
   topic_0: 66080 //no other topic is picked till topic_0 reaches 100k
}
=> 102035, { 
  topic_0: 100000,
  topic_4: 2035 //count stops at 2035 & picks another topic
}
=> 102076, { topic_0: 100000,
  topic_4: 2035,
  topic_1: 41 
}
=> 104088, { 
  topic_0: 100000,
  topic_4: 2035,
  topic_1: 2036, //count stops here and picks another topic
  topic_2: 18 
}
=> 105119, { 
  topic_0: 100000,
  topic_4: 2035,
  topic_1: 2036,
  topic_2: 1048 
}
=> 106108, { 
  topic_0: 100000,
  topic_4: 2035,
  topic_1: 2036,
  topic_2: 2036, //stops here
  topic_3: 1 
}
=> 108666, { 
  topic_0: 100000,
  topic_4: 2559, //this starts increasing till 4069 and then topic_1 is picked. 
  topic_1: 2036,
  topic_2: 2036,
  topic_3: 2034 //stops here
} 
=> 110262, { 
  topic_0: 100000,
  topic_4: 4069,
  topic_1: 2122, //till 4072 and topic_2 is picked
  topic_2: 2036,
  topic_3: 2034 
}

**Comment by sanketdhoble** [comment]
When I update node-rdkafka to latest version: 2.7.4
The behaviour is again different.  
Consumer picks each topic one at a time in sequence. ie topic_0 is consumed completely then topic_1 initiates and once topic_1 is finished completely then topic_2 starts and so on.

**Comment by codeburke** [comment]
Are the consumer's in the same process? I'm a bit confused on the test you described.

**Comment by sanketdhoble** [comment]
@codeburke 
Yes, consumers are in same process.
Consumer does not pick equally from all the topics when having large data (msgs>200kl).

**Comment by Tapppi** [comment]
Your issue describes producer configs for a consumer issue, that is not very useful. As for the 
processing order, AFAIK there is no documented guarantee about topic-partition processing order in this library nor in `librdkafka`, although I'm not knowledgeable enough about the c++ layer to say if `librdkafka` matters in this. Why do you want it to "pick equally from all the topics" in the first place? Usually if you want processing order guarantees, it will revolve around timestamps or some other ordering mechanism between the topics and that is more Kafka Streams stuff than fairly low-level-lib like `node-rdkafka`.

**Comment by codeburke** [comment]
I believe, from my understanding the `librdkafka` C++ API that node-rdkafka is built on, that all the messages are processed into a single message queue for simplicity.  The TL;DR (as far as I understand it) from reading the following `librdkafka` Issues is that the way the topic-partitions are processed is per broker and in a set order for that broker and up to 
`queued.min.messages` or `queued.max.messages.kbytes`. In this C++ API the `queued.min.messages` and `queued.max.messages.kbytes` values are set on the single queue instead of per topic-partition. This means that for a particular broker a single partition will be drained in a quasi-deterministic order and it will be especially apparent in the case of having a large consumer lag in many partitions on startup.

The work-around described in the Issues is to poll each assigned partition individually via the C API instead of link them all to a single message queue. That involves more complicated C code, some additional `poll` calls for rebalance_cb handling and also has the side effect of increasing the potential total amount of memory used to be `num of partitions assigned *  queued.max.messages`.

The con is this would be a fairly large change to underlying C++ wrapper in `node-rdkafka` to support this type of per-partition polling. The benefit is that it would help be more "fair" in certain runtime conditions to drain queues when there are large consumers lags.

https://github.com/edenhill/librdkafka/issues/1395
https://github.com/edenhill/librdkafka/issues/2312

**Comment by rakshitshah7** [comment]
I am facing a similar issue, was anyone able to fix this?
