### ISSUE TITLE
Segmentation fault after connect, before "ready" event

### ISSUE THREAD

**Issue by parkerse64** [Blizzard/node-rdkafka#761]
**Environment Information**
 - OS : Linux Sun Feb 9 00:23:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Node Version: v 10.19.0
 - NPM Version: 6.13.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version: 2.7.4

**Steps to Reproduce**

1. I have a kafka server on cloudkarafka.com
2. I'm using the code sample at  https://github.com/CloudKarafka/nodejs-kafka-example
3. Running: node consumer.js results in a segmentation fault
4. The segmentation fault appears to be after a successful connection to the server, but before the "ready" event.
5. The last message from event.log is: [thrd:sasl_ssl://moped-03.srvs.cloudkafka.com:9094/bootstrap]: sasl_ssl://moped-03.srvs.cloudkafka.com:9094/bootstrap: Connected to ipv4#3.83.18.175:9094

**node-rdkafka Configuration Settings**

var kafkaConf = {
  "group.id": "cloudkarafka-example",
  "metadata.broker.list": process.env.CLOUDKARAFKA_BROKERS.split(","),
  "socket.keepalive.enable": true,
  "security.protocol": "SASL_SSL",
  "sasl.mechanisms": "SCRAM-SHA-256",
  "sasl.username": process.env.CLOUDKARAFKA_USERNAME,
  "sasl.password": process.env.CLOUDKARAFKA_PASSWORD,
  "debug" : "generic,broker,security"
};

const prefix = process.env.CLOUDKARAFKA_USERNAME;
const topics = [`${prefix}.test`];
const consumer = new Kafka.KafkaConsumer(kafkaConf, {
  "auto.offset.reset": "beginning"
});

**Additional context**
The CLOUDKARAFKA_ variables are set per information from cloudkarafa for my server

**Comment by fg0217** [comment]
@parkerse64 I went down to the rabbit hole, debugging the issue. Assuming the issue is the same, I found that the problem is an error with the OpenSSL integration. I manually upgraded to OpenSSL 1.1 (https://askubuntu.com/questions/1102803/how-to-upgrade-openssl-1-1-0-to-1-1-1-in-ubuntu-18-04). After that, I had to remove my node_modules file again so that my program's librdkafka links against the new OpenSSL version and it worked. I hope that helps you too.
