### ISSUE TITLE
Authentication with SASL_SSL/OAUTHBEARER

### ISSUE THREAD

**Issue by klalafaryan** [Blizzard/node-rdkafka#812]
Hey all.

We have secured kafka cluster which supports SASL_SSL authentication. And we would like to connect using `node-rdkafka` lib.

Do you know if it is supported by `node-rdkafka`? If yes, where can I find a small sample ?

Thanks

**Comment by giulliano-bueno** [comment]
@klalafaryan *node-rdkafka* seems to not support *OAUTHBEARER* since it does not implement the callback necessary to refresh/get the token and passing a Node callback doesn't work because we can't call `RdKafka::oauthbearer_set_token()` directly from it. Check this Librdkafka header [here](https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L642), please.

**Comment by giulliano-bueno** [comment]
I am working on a pull request to fix this.

**Comment by elidelima** [comment]
> I am working on a pull request to fix this.

Hello @giulliano-bueno, 

Is there any updates on this issue?

Thanks

**Comment by giulliano-bueno** [comment]
> > I am working on a pull request to fix this.
> 
> Hello @giulliano-bueno,
> 
> Is there any updates on this issue?
> 
> Thanks

Hey Eli, I actually end up using a different library called KafkaJS since they merged this feature before I finished my work.
