### ISSUE TITLE
Memory Leak while Using Standard API for Producing data into a Kafka Topic 

### ISSUE THREAD

**Issue by rabeeshcharles** [Blizzard/node-rdkafka#849]
Os - Windows
Rd-Kafka - v2.9.1

Standard API
------------------
producer.produce('Topic_Name', null, 'Sample Msg', null, Date.now(), (err, offset) => {});

Steps to reproducing the issue
-----------------------------------
- Getting Memory Leak While trying to producing the data into a Kafka Topic based on stand API Method..
- So I Kindly help me out from this issue..

Thanks in Advance...

**Comment by Denusdv** [comment]
Hi rabeeshcharles 
 
I guess the issue you reported is the same I faced with 
https://github.com/Blizzard/node-rdkafka/issues/846

based on your sample, you are trying and following the documentation 

```
 * When this is sent off, there is no guarantee it is delivered. If you need
 * guaranteed delivery, change your *acks* settings, or use delivery reports.
 *
 * @param {string} topic - The topic name to produce to.
 * @param {number|null} partition - The partition number to produce to.
 * @param {Buffer|null} message - The message to produce.
 * @param {string} key - The key associated with the message.
 * @param {number|null} timestamp - Timestamp to send with the message.
 * @param {object} opaque - An object you want passed along with this message, if provided.
 * @param {object} headers - A list of custom key value pairs that provide message metadata.
 * @throws {LibrdKafkaError} - Throws a librdkafka error if it failed.
 * @return {boolean} - returns an error if it failed, or true if not
 * @see Producer#produce
 */
Producer.prototype.produce = function(topic, partition, message, key, timestamp, opaque, headers) {
  if (!this._isConnected) {
    throw new Error('Producer not connected');
  }
```

The **opaque** argument in your case is a function. ( not sure I'm getting you code completely but it's not the point). In my case I was trying to attach a header to the kafka message.  In my call I'm getting memory leak even if I provide nulls as values for last two arguments. Pls read my question. 

Unfortunately I haven't gotten any reply yet. I very hope our questions will be addressed, since I'm waiting for more than a month for any comment .

**Comment by rabeeshcharles** [comment]
Hi @Denusdv ,

I have read your question and i have also followed the rdkafka documentation to get the sample code.
 Im also getting a memory leak while producing a msg in a kafka topic without headers and key..Im also waiting for the reply..

**Comment by iradul** [comment]
As @Denusdv explained if you pass function to the opaque argument you'll see memory leak. Remove `, (err, offset) => {}`
