### ISSUE TITLE
Not able to consume messages if group.id is not provided

### ISSUE THREAD

**Issue by gshrib** [Blizzard/node-rdkafka#858]
Have a scenario like same consumer code instance needs to run in 2000 servers. each server instances should need to read all the topic partitions and only one instance will run in each server. So, my scenario don't need group.id but, without group.id consumer is not ready and not consuming messages. any thoughts how to handle this scenario?

**Comment by ViktorWb** [comment]
See [this issue](https://github.com/edenhill/librdkafka/issues/593) discussed over at librdkafka. It seems that `group.id` is required, but will actually only be sent to the broker if you use the subscribe API, or when committing offsets. So in theory you should be able to set it to anything and it should be unused if you don't use these functions.

I can think of two approaches to your problem:
- Use a unique group.id for each consumer.
- Set `group.id` to anything (it will not be used), `enable.auto.commit` to  false, and use the `assign` API instead of `subscribe`. This should allow you to read messages from any partition without a consumer group. The downside is that you will not be able to commit messages, since this requires a group.id. Instead you can control which messages to consume by the configuration `auto.offset.reset` ([configuration.md](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)).
